tests
testDataAPI

	self
		assert: BootstrapDatepickerConstants autoclose equals: 'date-autoclose';
		assert: BootstrapDatepickerConstants forceParse equals: 'date-force-parse';
		assert: BootstrapDatepickerConstants keyboardNavigation equals: 'date-keyboard-navigation';
		assert: BootstrapDatepickerConstants language equals: 'date-language';
		assert: BootstrapDatepickerConstants orientation equals: 'date-orientation';
		assert: BootstrapDatepickerConstants todayButton equals: 'date-today-btn';
		assert: BootstrapDatepickerConstants todayHighlight equals: 'date-today-highlight'