Updating
updateRoot: aRoot

	aRoot stylesheet
		url: ('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/<1s>/css/bootstrap-datepicker3.min.css' expandMacrosWith: self version);
		anonymousSubResourceIntegrity: 'sha256-1iqXk6r3x/0/ipzsJOLDhuaMkmluaS1yhkM5MmQr5WU='.
	aRoot javascript
		url: ('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/<1s>/js/bootstrap-datepicker.min.js' expandMacrosWith: self version);
		anonymousSubResourceIntegrity: 'sha256-WjqKRLVPOKXTLplqPZyHgfV+KmQu8JulAuQVHdXUcJU='