tests
testIcons4

	self
		assert: Glyphicons piggyBank equals: 'glyphicon-piggy-bank';
		assert: Glyphicons scissors equals: 'glyphicon-scissors';
		assert: Glyphicons bitcoin equals: 'glyphicon-bitcoin';
		assert: Glyphicons btc equals: 'glyphicon-btc';
		assert: Glyphicons xbt equals: 'glyphicon-xbt';
		assert: Glyphicons yen equals: 'glyphicon-yen';
		assert: Glyphicons jpy equals: 'glyphicon-jpy';
		assert: Glyphicons ruble equals: 'glyphicon-ruble';
		assert: Glyphicons rub equals: 'glyphicon-rub';
		assert: Glyphicons scale equals: 'glyphicon-scale';
		assert: Glyphicons iceLolly equals: 'glyphicon-ice-lolly';
		assert: Glyphicons iceLollyTasted equals: 'glyphicon-ice-lolly-tasted';
		assert: Glyphicons education equals: 'glyphicon-education';
		assert: Glyphicons optionHorizontal equals: 'glyphicon-option-horizontal';
		assert: Glyphicons optionVertical equals: 'glyphicon-option-vertical';
		assert: Glyphicons menuHamburger equals: 'glyphicon-menu-hamburger';
		assert: Glyphicons modalWindow equals: 'glyphicon-modal-window';
		assert: Glyphicons oil equals: 'glyphicon-oil';
		assert: Glyphicons grain equals: 'glyphicon-grain';
		assert: Glyphicons sunglasses equals: 'glyphicon-sunglasses';
		assert: Glyphicons textSize equals: 'glyphicon-text-size';
		assert: Glyphicons textColor equals: 'glyphicon-text-color';
		assert: Glyphicons textBackground equals: 'glyphicon-text-background';
		assert: Glyphicons objectAlignTop equals: 'glyphicon-object-align-top';
		assert: Glyphicons objectAlignBottom equals: 'glyphicon-object-align-bottom';
		assert: Glyphicons objectAlignHorizontal equals: 'glyphicon-object-align-horizontal';
		assert: Glyphicons objectAlignLeft equals: 'glyphicon-object-align-left';
		assert: Glyphicons objectAlignVertical equals: 'glyphicon-object-align-vertical';
		assert: Glyphicons objectAlignRight equals: 'glyphicon-object-align-right';
		assert: Glyphicons triangleRight equals: 'glyphicon-triangle-right';
		assert: Glyphicons triangleLeft equals: 'glyphicon-triangle-left';
		assert: Glyphicons triangleBottom equals: 'glyphicon-triangle-bottom';
		assert: Glyphicons triangleTop equals: 'glyphicon-triangle-top';
		assert: Glyphicons console equals: 'glyphicon-console';
		assert: Glyphicons superscript equals: 'glyphicon-superscript';
		assert: Glyphicons subscript equals: 'glyphicon-subscript';
		assert: Glyphicons menuLeft equals: 'glyphicon-menu-left';
		assert: Glyphicons menuRight equals: 'glyphicon-menu-right';
		assert: Glyphicons menuDown equals: 'glyphicon-menu-down';
		assert: Glyphicons menuUp equals: 'glyphicon-menu-up'