tests
testDataAPI

	self
		assert: BootstrapSelectConstants selectedTextFormat equals: 'selected-text-format';
		assert: BootstrapSelectConstants noneSelectedText equals: 'none-selected-text';
		assert: BootstrapSelectConstants width equals: 'width';
		assert: BootstrapSelectConstants actionsBox equals: 'actions-box';
		assert: BootstrapSelectConstants container equals: 'container';
		assert: BootstrapSelectConstants countSelectedText equals: 'count-selected-text';
		assert: BootstrapSelectConstants deselectAllText equals: 'deselect-all-text';
		assert: BootstrapSelectConstants dropdownAlignRight equals: 'dropdown-align-right';
		assert: BootstrapSelectConstants dropupAuto equals: 'dropup-auto';
		assert: BootstrapSelectConstants header equals: 'header';
		assert: BootstrapSelectConstants hideDisabled equals: 'hide-disabled';
		assert: BootstrapSelectConstants iconBase equals: 'icon-base';
		assert: BootstrapSelectConstants liveSearch equals: 'live-search';
		assert: BootstrapSelectConstants liveSearchNormalize equals: 'live-search-normalize';
		assert: BootstrapSelectConstants liveSearchPlaceholder equals: 'live-search-placeholder';
		assert: BootstrapSelectConstants liveSearchStyle equals: 'live-search-style';
		assert: BootstrapSelectConstants maxOptions equals: 'max-options';
		assert: BootstrapSelectConstants maxOptionsText equals: 'max-options-text';
		assert: BootstrapSelectConstants mobile equals: 'mobile';
		assert: BootstrapSelectConstants multipleSeparator equals: 'multiple-separator';
		assert: BootstrapSelectConstants selectAllText equals: 'select-all-text';
		assert: BootstrapSelectConstants selectOnTab equals: 'select-on-tab';
		assert: BootstrapSelectConstants showContent equals: 'show-content';
		assert: BootstrapSelectConstants showIcon equals: 'show-icon';
		assert: BootstrapSelectConstants showSubtext equals: 'show-subtext';
		assert: BootstrapSelectConstants showTick equals: 'show-tick';
		assert: BootstrapSelectConstants style equals: 'style';
		assert: BootstrapSelectConstants tickIcon equals: 'tick-icon';
		assert: BootstrapSelectConstants title equals: 'title';
		assert: BootstrapSelectConstants windowPadding equals: 'window-padding'