Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertDark [

	^ self commandStyledWith: #alertDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertHeading [

	^ self commandStyledWith: #alertHeading
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertLight [

	^ self commandStyledWith: #alertLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertPrimary [

	^ self commandStyledWith: #alertPrimary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertSecondary [

	^ self commandStyledWith: #alertSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundDark [

	^ self commandStyledWith: #backgroundDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientDanger [

	^ self commandStyledWith: #backgroundGradientDanger
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientDark [

	^ self commandStyledWith: #backgroundGradientDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientInfo [

	^ self commandStyledWith: #backgroundGradientInfo
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientLight [

	^ self commandStyledWith: #backgroundGradientLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientPrimary [

	^ self commandStyledWith: #backgroundGradientPrimary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientSecondary [

	^ self commandStyledWith: #backgroundGradientSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientSuccess [

	^ self commandStyledWith: #backgroundGradientSuccess
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundGradientWarning [

	^ self commandStyledWith: #backgroundGradientWarning
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundLight [

	^ self commandStyledWith: #backgroundLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundSecondary [

	^ self commandStyledWith: #backgroundSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundTransparent [

	^ self commandStyledWith: #backgroundTransparent
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> backgroundWhite [

	^ self commandStyledWith: #backgroundWhite
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> bootstrap4 [

	classificationNamespace := classificationNamespace >> #bootstrap4
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> breadcrumbItem [

	^ self commandStyledWith: #breadcrumbItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> carDeck [

	^ self commandStyledWith: #carDeck
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> card [

	^ self commandStyledWith: #card
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardBody [

	^ self commandStyledWith: #cardBody
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardColumns [

	^ self commandStyledWith: #cardColumns
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardFooter [

	^ self commandStyledWith: #cardFooter
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardGroup [

	^ self commandStyledWith: #cardGroup
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardHeader [

	^ self commandStyledWith: #cardHeader
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardImage [

	^ self commandStyledWith: #cardImage
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardImageOverlay [

	^ self commandStyledWith: #cardImageOverlay
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardImageTop [

	^ self commandStyledWith: #cardImageTop
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardLink [

	^ self commandStyledWith: #cardLink
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardSubtitle [

	^ self commandStyledWith: #cardSubtitle
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardText [

	^ self commandStyledWith: #cardText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> cardTitle [

	^ self commandStyledWith: #cardTitle
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> columnFormLabel [

	^ self commandStyledWith: #columnFormLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> columnFormLabelLarge [

	^ self commandStyledWith: #columnFormLabelLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> columnFormLabelSmall [

	^ self commandStyledWith: #columnFormLabelSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customCheckbox [

	^ self commandStyledWith: #customCheckbox
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControl [

	^ self commandStyledWith: #customControl
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControlInline [

	^ self commandStyledWith: #customControlInline
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControlInput [

	^ self commandStyledWith: #customControlInput
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControlLabel [

	^ self commandStyledWith: #customControlLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customFile [

	^ self commandStyledWith: #customFile
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customFileInput [

	^ self commandStyledWith: #customFileInput
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customFileLabel [

	^ self commandStyledWith: #customFileLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customRadio [

	^ self commandStyledWith: #customRadio
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customRange [

	^ self commandStyledWith: #customRange
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSelect [

	^ self commandStyledWith: #customSelect
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSelectLarge [

	^ self commandStyledWith: #customSelectLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSelectSmall [

	^ self commandStyledWith: #customSelectSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSwitch [

	^ self commandStyledWith: #customSwitch
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownDivider [

	^ self commandStyledWith: #dropdownDivider
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownItem [

	^ self commandStyledWith: #dropdownItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownItemText [

	^ self commandStyledWith: #dropdownItemText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownToggleSplit [

	^ self commandStyledWith: #dropdownToggleSplit
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropleft [

	^ self commandStyledWith: #dropleft
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropright [

	^ self commandStyledWith: #dropright
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> fixedBottom [

	^ self commandStyledWith: #fixedBottom
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> fixedTop [

	^ self commandStyledWith: #fixedTop
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> flexColumn [

	^ self commandStyledWith: #flexColumn
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> flexColumnReverse [

	^ self commandStyledWith: #flexColumnReverse
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> flexRow [

	^ self commandStyledWith: #flexRow
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> flexRowReverse [

	^ self commandStyledWith: #flexRowReverse
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheck [

	^ self commandStyledWith: #formCheck
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheckInline [

	^ self commandStyledWith: #formCheckInline
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheckInput [

	^ self commandStyledWith: #formCheckInput
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheckLabel [

	^ self commandStyledWith: #formCheckLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlFile [

	^ self commandStyledWith: #formControlFile
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlLarge [

	^ self commandStyledWith: #formControlLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlPlainText [

	^ self commandStyledWith: #formControlPlainText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlRange [

	^ self commandStyledWith: #formControlRange
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlSmall [

	^ self commandStyledWith: #formControlSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formRow [

	^ self commandStyledWith: #formRow
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formText [

	^ self commandStyledWith: #formText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> inputGroupAppend [

	^ self commandStyledWith: #inputGroupAppend
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> inputGroupPrepend [

	^ self commandStyledWith: #inputGroupPrepend
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> inputGroupText [

	^ self commandStyledWith: #inputGroupText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> invalidFeedback [

	^ self commandStyledWith: #invalidFeedback
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> invalidTooltip [

	^ self commandStyledWith: #invalidTooltip
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> isInvalid [

	^ self commandStyledWith: #isInvalid
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> isValid [

	^ self commandStyledWith: #isValid
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> justifyContentAround [

	^ self commandStyledWith: #justifyContentAround
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> justifyContentBetween [

	^ self commandStyledWith: #justifyContentBetween
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> justifyContentCenter [

	^ self commandStyledWith: #justifyContentCenter
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> justifyContentEnd [

	^ self commandStyledWith: #justifyContentEnd
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> justifyContentStart [

	^ self commandStyledWith: #justifyContentStart
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupFlush [

	^ self commandStyledWith: #listGroupFlush
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupHorizontal [

	^ self commandStyledWith: #listGroupHorizontal
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupHorizontalExtraSmall [

	^ self commandStyledWith: #listGroupHorizontalExtraSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupHorizontalLarge [

	^ self commandStyledWith: #listGroupHorizontalLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupHorizontalMedium [

	^ self commandStyledWith: #listGroupHorizontalMedium
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupHorizontalSmall [

	^ self commandStyledWith: #listGroupHorizontalSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupItemAction [

	^ self commandStyledWith: #listGroupItemAction
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupItemDark [

	^ self commandStyledWith: #listGroupItemDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupItemLight [

	^ self commandStyledWith: #listGroupItemLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupItemPrimary [

	^ self commandStyledWith: #listGroupItemPrimary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> listGroupItemSecondary [

	^ self commandStyledWith: #listGroupItemSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> modalDialogCentered [

	^ self commandStyledWith: #modalDialogCentered
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> modalDialogScrollable [

	^ self commandStyledWith: #modalDialogScrollable
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> modalExtraLarge [

	^ self commandStyledWith: #modalExtraLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navFill [

	^ self commandStyledWith: #navFill
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navItem [

	^ self commandStyledWith: #navItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navLink [

	^ self commandStyledWith: #navLink
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarDark [

	^ self commandStyledWith: #navbarDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpand [

	^ self commandStyledWith: #navbarExpand
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandExtraLarge [

	^ self commandStyledWith: #navbarExpandExtraLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandLarge [

	^ self commandStyledWith: #navbarExpandLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandMedium [

	^ self commandStyledWith: #navbarExpandMedium
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandSmall [

	^ self commandStyledWith: #navbarExpandSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarLight [

	^ self commandStyledWith: #navbarLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarToggler [

	^ self commandStyledWith: #navbarToggler
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarTogglerIcon [

	^ self commandStyledWith: #navbarTogglerIcon
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> popoverBody [

	^ self commandStyledWith: #popoverBody
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> popoverHeader [

	^ self commandStyledWith: #popoverHeader
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionAbsolute [

	^ self commandStyledWith: #positionAbsolute
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionFixed [

	^ self commandStyledWith: #positionFixed
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionRelative [

	^ self commandStyledWith: #positionRelative
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionStatic [

	^ self commandStyledWith: #positionStatic
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionSticky [

	^ self commandStyledWith: #positionSticky
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> stickyTop [

	^ self commandStyledWith: #stickyTop
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textBlack50 [

	^ self commandStyledWith: #textBlack50
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textBody [

	^ self commandStyledWith: #textBody
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textDark [

	^ self commandStyledWith: #textDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textLight [

	^ self commandStyledWith: #textLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textSecondary [

	^ self commandStyledWith: #textSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textWhite [

	^ self commandStyledWith: #textWhite
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> textWhite50 [

	^ self commandStyledWith: #textWhite50
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> validFeedback [

	^ self commandStyledWith: #validFeedback
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> validTooltip [

	^ self commandStyledWith: #validTooltip
]
