Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertDark [

	^ self commandStyledWith: #alertDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertHeading [

	^ self commandStyledWith: #alertHeading
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertLight [

	^ self commandStyledWith: #alertLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertPrimary [

	^ self commandStyledWith: #alertPrimary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertSecondary [

	^ self commandStyledWith: #alertSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> bootstrap4 [

	classificationNamespace := classificationNamespace >> #bootstrap4
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> breadcrumbItem [

	^ self commandStyledWith: #breadcrumbItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownDivider [

	^ self commandStyledWith: #dropdownDivider
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownItem [

	^ self commandStyledWith: #dropdownItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownItemText [

	^ self commandStyledWith: #dropdownItemText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownToggleSplit [

	^ self commandStyledWith: #dropdownToggleSplit
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropleft [

	^ self commandStyledWith: #dropleft
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropright [

	^ self commandStyledWith: #dropright
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navFill [

	^ self commandStyledWith: #navFill
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navItem [

	^ self commandStyledWith: #navItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navLink [

	^ self commandStyledWith: #navLink
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarDark [

	^ self commandStyledWith: #navbarDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpand [

	^ self commandStyledWith: #navbarExpand
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandExtraLarge [

	^ self commandStyledWith: #navbarExpandExtraLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandLarge [

	^ self commandStyledWith: #navbarExpandLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandMedium [

	^ self commandStyledWith: #navbarExpandMedium
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandSmall [

	^ self commandStyledWith: #navbarExpandSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarLight [

	^ self commandStyledWith: #navbarLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarToggler [

	^ self commandStyledWith: #navbarToggler
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarTogglerIcon [

	^ self commandStyledWith: #navbarTogglerIcon
]
