Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertDark [

	^ self commandStyledWith: #alertDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertHeading [

	^ self commandStyledWith: #alertHeading
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertLight [

	^ self commandStyledWith: #alertLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertPrimary [

	^ self commandStyledWith: #alertPrimary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> alertSecondary [

	^ self commandStyledWith: #alertSecondary
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> bootstrap4 [

	classificationNamespace := classificationNamespace >> #bootstrap4
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> breadcrumbItem [

	^ self commandStyledWith: #breadcrumbItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> columnFormLabel [

	^ self commandStyledWith: #columnFormLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> columnFormLabelLarge [

	^ self commandStyledWith: #columnFormLabelLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> columnFormLabelSmall [

	^ self commandStyledWith: #columnFormLabelSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customCheckbox [

	^ self commandStyledWith: #customCheckbox
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControl [

	^ self commandStyledWith: #customControl
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControlInline [

	^ self commandStyledWith: #customControlInline
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControlInput [

	^ self commandStyledWith: #customControlInput
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customControlLabel [

	^ self commandStyledWith: #customControlLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customFile [

	^ self commandStyledWith: #customFile
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customFileInput [

	^ self commandStyledWith: #customFileInput
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customFileLabel [

	^ self commandStyledWith: #customFileLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customRadio [

	^ self commandStyledWith: #customRadio
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customRange [

	^ self commandStyledWith: #customRange
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSelect [

	^ self commandStyledWith: #customSelect
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSelectLarge [

	^ self commandStyledWith: #customSelectLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSelectSmall [

	^ self commandStyledWith: #customSelectSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> customSwitch [

	^ self commandStyledWith: #customSwitch
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownDivider [

	^ self commandStyledWith: #dropdownDivider
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownItem [

	^ self commandStyledWith: #dropdownItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownItemText [

	^ self commandStyledWith: #dropdownItemText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropdownToggleSplit [

	^ self commandStyledWith: #dropdownToggleSplit
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropleft [

	^ self commandStyledWith: #dropleft
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> dropright [

	^ self commandStyledWith: #dropright
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> fixedBottom [

	^ self commandStyledWith: #fixedBottom
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> fixedTop [

	^ self commandStyledWith: #fixedTop
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheck [

	^ self commandStyledWith: #formCheck
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheckInline [

	^ self commandStyledWith: #formCheckInline
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheckInput [

	^ self commandStyledWith: #formCheckInput
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formCheckLabel [

	^ self commandStyledWith: #formCheckLabel
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlFile [

	^ self commandStyledWith: #formControlFile
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlLarge [

	^ self commandStyledWith: #formControlLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlPlainText [

	^ self commandStyledWith: #formControlPlainText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlRange [

	^ self commandStyledWith: #formControlRange
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formControlSmall [

	^ self commandStyledWith: #formControlSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formRow [

	^ self commandStyledWith: #formRow
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> formText [

	^ self commandStyledWith: #formText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> inputGroupAppend [

	^ self commandStyledWith: #inputGroupAppend
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> inputGroupPrepend [

	^ self commandStyledWith: #inputGroupPrepend
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> inputGroupText [

	^ self commandStyledWith: #inputGroupText
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> invalidFeedback [

	^ self commandStyledWith: #invalidFeedback
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> invalidTooltip [

	^ self commandStyledWith: #invalidTooltip
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> isInvalid [

	^ self commandStyledWith: #isInvalid
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> isValid [

	^ self commandStyledWith: #isValid
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navFill [

	^ self commandStyledWith: #navFill
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navItem [

	^ self commandStyledWith: #navItem
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navLink [

	^ self commandStyledWith: #navLink
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarDark [

	^ self commandStyledWith: #navbarDark
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpand [

	^ self commandStyledWith: #navbarExpand
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandExtraLarge [

	^ self commandStyledWith: #navbarExpandExtraLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandLarge [

	^ self commandStyledWith: #navbarExpandLarge
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandMedium [

	^ self commandStyledWith: #navbarExpandMedium
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarExpandSmall [

	^ self commandStyledWith: #navbarExpandSmall
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarLight [

	^ self commandStyledWith: #navbarLight
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarToggler [

	^ self commandStyledWith: #navbarToggler
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> navbarTogglerIcon [

	^ self commandStyledWith: #navbarTogglerIcon
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionAbsolute [

	^ self commandStyledWith: #positionAbsolute
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionFixed [

	^ self commandStyledWith: #positionFixed
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionRelative [

	^ self commandStyledWith: #positionRelative
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionStatic [

	^ self commandStyledWith: #positionStatic
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> positionSticky [

	^ self commandStyledWith: #positionSticky
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> stickyTop [

	^ self commandStyledWith: #stickyTop
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> validFeedback [

	^ self commandStyledWith: #validFeedback
]

{ #category : #'*Willow-Bootstrap-4' }
ComponentClassificationCommandBuilder >> validTooltip [

	^ self commandStyledWith: #validTooltip
]
