SystemOrganization addCategory: #'Willow-Bootstrap'!
SystemOrganization addCategory: 'Willow-Bootstrap-Datepicker'!
SystemOrganization addCategory: 'Willow-Bootstrap-Frontend'!
SystemOrganization addCategory: 'Willow-Bootstrap-Libraries'!
SystemOrganization addCategory: 'Willow-Bootstrap-Plugins'!
SystemOrganization addCategory: 'Willow-Bootstrap-Select'!
SystemOrganization addCategory: 'Willow-Bootstrap-Typeahead'!
SystemOrganization addCategory: 'Willow-Bootstrap-WebViews'!
