"
Bootstrap specific constants
"
Class {
	#name : #BootstrapConstants,
	#superclass : #Object,
	#category : #'Willow-Bootstrap-WebViews'
}

{ #category : #Roles }
BootstrapConstants class >> alert [

	^ 'alert'
]

{ #category : #'Data-API' }
BootstrapConstants class >> animation [

	^ 'animation'
]

{ #category : #'Data-API' }
BootstrapConstants class >> backdrop [

	^ 'backdrop'
]

{ #category : #Roles }
BootstrapConstants class >> button [

	^ 'button'
]

{ #category : #'Data-API' }
BootstrapConstants class >> buttons [

	^ 'buttons'
]

{ #category : #'Willow Functions' }
BootstrapConstants class >> cleanModalFunctionName [

	^ 'cleanModal'
]

{ #category : #'Data-API' }
BootstrapConstants class >> click [

	^ 'click'
]

{ #category : #'Data-API' }
BootstrapConstants class >> container [

	^ 'container'
]

{ #category : #'Data-API' }
BootstrapConstants class >> content [

	^ 'content'
]

{ #category : #'Data-API' }
BootstrapConstants class >> delay [

	^ 'delay'
]

{ #category : #Roles }
BootstrapConstants class >> dialog [

	^ 'dialog'
]

{ #category : #'Data-API' }
BootstrapConstants class >> dismiss [

	^ 'dismiss'
]

{ #category : #Roles }
BootstrapConstants class >> document [

	^ 'document'
]

{ #category : #'Data-API' }
BootstrapConstants class >> dropdown [

	^ 'dropdown'
]

{ #category : #'Data-API' }
BootstrapConstants class >> focus [

	^ 'focus'
]

{ #category : #Roles }
BootstrapConstants class >> group [

	^ 'group'
]

{ #category : #Events }
BootstrapConstants class >> hiddenCollapse [

	^ 'hidden.bs.collapse'
]

{ #category : #Events }
BootstrapConstants class >> hiddenDropdown [

	^ 'hidden.bs.dropdown'
]

{ #category : #Events }
BootstrapConstants class >> hiddenModal [

	^ 'hidden.bs.modal'
]

{ #category : #Events }
BootstrapConstants class >> hiddenPopover [

	^ 'hidden.bs.popover'
]

{ #category : #Events }
BootstrapConstants class >> hiddenTooltip [

	^ 'hidden.bs.tooltip'
]

{ #category : #Events }
BootstrapConstants class >> hideCollapse [

	^ 'hide.bs.collapse'
]

{ #category : #Events }
BootstrapConstants class >> hideDropdown [

	^ 'hide.bs.dropdown'
]

{ #category : #Events }
BootstrapConstants class >> hideModal [

	^ 'hide.bs.modal'
]

{ #category : #Events }
BootstrapConstants class >> hidePopover [

	^ 'hide.bs.popover'
]

{ #category : #Events }
BootstrapConstants class >> hideTooltip [

	^ 'hide.bs.tooltip'
]

{ #category : #'Data-API' }
BootstrapConstants class >> hover [

	^ 'hover'
]

{ #category : #'Data-API' }
BootstrapConstants class >> html [

	^ 'html'
]

{ #category : #Events }
BootstrapConstants class >> insertedPopover [

	^ 'inserted.bs.popover'
]

{ #category : #Events }
BootstrapConstants class >> insertedTooltip [

	^ 'inserted.bs.tooltip'
]

{ #category : #'Data-API' }
BootstrapConstants class >> keyboard [

	^ 'keyboard'
]

{ #category : #'Data-API' }
BootstrapConstants class >> manual [

	^ 'manual'
]

{ #category : #'Data-API' }
BootstrapConstants class >> modal [

	^ 'modal'
]

{ #category : #Roles }
BootstrapConstants class >> navigation [

	^ 'navigation'
]

{ #category : #'Data-API' }
BootstrapConstants class >> parent [

	^ 'parent'
]

{ #category : #'Data-API' }
BootstrapConstants class >> pill [

	^ 'pill'
]

{ #category : #'Data-API' }
BootstrapConstants class >> placement [

	^ 'placement'
]

{ #category : #'Data-API' }
BootstrapConstants class >> popover [

	^ 'popover'
]

{ #category : #Roles }
BootstrapConstants class >> presentation [

	^ 'presentation'
]

{ #category : #Roles }
BootstrapConstants class >> progressbar [

	^ 'progressbar'
]

{ #category : #'Data-API' }
BootstrapConstants class >> role [

	^ 'role'
]

{ #category : #'Data-API' }
BootstrapConstants class >> selector [

	^ 'selector'
]

{ #category : #Roles }
BootstrapConstants class >> separator [

	^ 'separator'
]

{ #category : #'Data-API' }
BootstrapConstants class >> show [

	^ 'show'
]

{ #category : #Events }
BootstrapConstants class >> showCollapse [

	^ 'show.bs.collapse'
]

{ #category : #Events }
BootstrapConstants class >> showDropdown [

	^ 'show.bs.dropdown'
]

{ #category : #Events }
BootstrapConstants class >> showModal [

	^ 'show.bs.modal'
]

{ #category : #Events }
BootstrapConstants class >> showPopover [

	^ 'show.bs.popover'
]

{ #category : #Events }
BootstrapConstants class >> showTooltip [

	^ 'show.bs.tooltip'
]

{ #category : #Events }
BootstrapConstants class >> shownCollapse [

	^ 'shown.bs.collapse'
]

{ #category : #Events }
BootstrapConstants class >> shownDropdown [

	^ 'shown.bs.dropdown'
]

{ #category : #Events }
BootstrapConstants class >> shownModal [

	^ 'shown.bs.modal'
]

{ #category : #Events }
BootstrapConstants class >> shownPopover [

	^ 'shown.bs.popover'
]

{ #category : #Events }
BootstrapConstants class >> shownTooltip [

	^ 'shown.bs.tooltip'
]

{ #category : #'Data-API' }
BootstrapConstants class >> static [

	^ 'static'
]

{ #category : #Roles }
BootstrapConstants class >> tab [

	^ 'tab'
]

{ #category : #Roles }
BootstrapConstants class >> tablist [

	^ 'tablist'
]

{ #category : #Roles }
BootstrapConstants class >> tabpanel [

	^ 'tabpanel'
]

{ #category : #'Data-API' }
BootstrapConstants class >> target [

	^ 'target'
]

{ #category : #'Data-API' }
BootstrapConstants class >> template [

	^ 'template'
]

{ #category : #'Data-API' }
BootstrapConstants class >> title [

	^ 'title'
]

{ #category : #'Data-API' }
BootstrapConstants class >> toggle [

	^ 'toggle'
]

{ #category : #Roles }
BootstrapConstants class >> toolbar [

	^ 'toolbar'
]

{ #category : #'Data-API' }
BootstrapConstants class >> trigger [

	^ 'trigger'
]

{ #category : #'Data-API' }
BootstrapConstants class >> viewport [

	^ 'viewport'
]
