"
I provide access to bootstrap-datepicker constants
"
Class {
	#name : #BootstrapDatepickerConstants,
	#superclass : #Object,
	#category : #'Willow-Bootstrap-Datepicker'
}

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> autoclose [

	^'date-autoclose'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> centuries [

	^'centuries'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> century [

	^'century'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> changeCentury [

	^ 'changeCentury'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> changeDate [

	^ 'changeDate'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> changeDecade [

	^ 'changeDecade'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> changeMonth [

	^ 'changeMonth'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> changeViewMode [

	^ 'changeViewMode'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> changeYear [

	^ 'changeYear'
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> clearDate [

	^ 'clearDate'
]

{ #category : #'Accessing - Classes' }
BootstrapDatepickerConstants class >> date [

	^ 'date'
]

{ #category : #'Accessing - Classes' }
BootstrapDatepickerConstants class >> datepicker [

	^ 'datepicker'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> days [

	^'days'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> decade [

	^'decade'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> decades [

	^'decades'
]

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> forceParse [

	^'date-force-parse'
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> friday [

	^ 5
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> hide [

	^ 'hide'
]

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> keyboardNavigation [

	^'date-keyboard-navigation'
]

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> language [

	^'date-language'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> linked [

	^'linked'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> millennium [

	^'millennium'
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> monday [

	^ 1
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> month [

	^'month'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> months [

	^'months'
]

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> orientation [

	^'date-orientation'
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> saturday [

	^ 6
]

{ #category : #'Accessing - Events' }
BootstrapDatepickerConstants class >> show [

	^ 'show'
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> sunday [

	^0
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> thursday [

	^ 4
]

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> todayButton [

	^'date-today-btn'
]

{ #category : #'Accessing - Data-API' }
BootstrapDatepickerConstants class >> todayHighlight [

	^'date-today-highlight'
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> tuesday [

	^ 2
]

{ #category : #'Accessing - Week Start' }
BootstrapDatepickerConstants class >> wednesday [

	^ 3
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> year [

	^'year'
]

{ #category : #'Accessing - View Modes' }
BootstrapDatepickerConstants class >> years [

	^'years'
]
