"
All the Bootstrap specific CSS classes
"
Class {
	#name : #BootstrapCssStyles,
	#superclass : #Object,
	#category : 'Willow-Bootstrap-WebViews'
}

{ #category : #Buttons }
BootstrapCssStyles class >> active [

	^ 'active'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alert [

	^ 'alert'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alertDanger [

	^ 'alert-danger'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alertDismissible [

	^ 'alert-dismissible'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alertInfo [

	^ 'alert-info'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alertLink [

	^ 'alert-link'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alertSuccess [

	^ 'alert-success'
]

{ #category : #Alerts }
BootstrapCssStyles class >> alertWarning [

	^ 'alert-warning'
]

{ #category : #Popover }
BootstrapCssStyles class >> arrow [

	^ 'arrow'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> backgroundDanger [

	^ 'bg-danger'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> backgroundInfo [

	^ 'bg-info'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> backgroundPrimary [

	^ 'bg-primary'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> backgroundSuccess [

	^ 'bg-success'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> backgroundWarning [

	^ 'bg-warning'
]

{ #category : #Labels }
BootstrapCssStyles class >> badge [

	^ 'badge'
]

{ #category : #Typography }
BootstrapCssStyles class >> blockquoteReverse [

	^ 'blockquote-reverse'
]

{ #category : #Navigation }
BootstrapCssStyles class >> breadcrumb [

	^ 'breadcrumb'
]

{ #category : #Buttons }
BootstrapCssStyles class >> button [

	^ 'btn'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonBlock [

	^ 'btn-block'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonDanger [

	^ 'btn-danger'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonDefault [

	^ 'btn-default'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonExtraSmall [

	^ 'btn-xs'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonGroup [

	^ 'btn-group'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonGroupExtraSmall [

	^ 'btn-group-xs'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonGroupJustified [

	^ 'btn-group-justified'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonGroupLarge [

	^ 'btn-group-lg'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonGroupSmall [

	^ 'btn-group-sm'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonGroupVertical [

	^ 'btn-group-vertical'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonInfo [

	^ 'btn-info'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonLarge [

	^ 'btn-lg'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonLink [

	^ 'btn-link'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonPrimary [

	^ 'btn-primary'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonSmall [

	^ 'btn-sm'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonSuccess [

	^ 'btn-success'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonToolbar [

	^ 'btn-toolbar'
]

{ #category : #Buttons }
BootstrapCssStyles class >> buttonWarning [

	^ 'btn-warning'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> caret [

	^ 'caret'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> centerBlock [

	^ 'center-block'
]

{ #category : #Forms }
BootstrapCssStyles class >> checkbox [

	^ 'checkbox'
]

{ #category : #Forms }
BootstrapCssStyles class >> checkboxInline [

	^ 'checkbox-inline'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> clearfix [

	^'clearfix'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> close [

	^ 'close'
]

{ #category : #Collapse }
BootstrapCssStyles class >> collapse [

	^'collapse'
]

{ #category : #Collapse }
BootstrapCssStyles class >> collapsed [

	^'collapsed'
]

{ #category : #Collapse }
BootstrapCssStyles class >> collapsing [

	^'collapsing'
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnExtraSmall: aColumnCount [

	^'col-xs-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnExtraSmallOffset: aColumnCount [

	^'col-xs-offset-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnExtraSmallPull: aColumnCount [

	^'col-xs-pull-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnExtraSmallPush: aColumnCount [

	^'col-xs-push-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnLarge: aColumnCount [

	^'col-lg-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnLargeOffset: aColumnCount [

	^'col-lg-offset-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnLargePull: aColumnCount [

	^'col-lg-pull-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnLargePush: aColumnCount [

	^'col-lg-push-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnMedium: aColumnCount [

	^'col-md-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnMediumOffset: aColumnCount [

	^'col-md-offset-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnMediumPull: aColumnCount [

	^'col-md-pull-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnMediumPush: aColumnCount [

	^'col-md-push-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnSmall: aColumnCount [

	^'col-sm-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnSmallOffset: aColumnCount [

	^'col-sm-offset-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnSmallPull: aColumnCount [

	^'col-sm-pull-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> columnSmallPush: aColumnCount [

	^'col-sm-push-<1p>' expandMacrosWith: aColumnCount 
]

{ #category : #Containers }
BootstrapCssStyles class >> container [

	^'container'
]

{ #category : #Containers }
BootstrapCssStyles class >> containerFluid [

	^'container-fluid'
]

{ #category : #Forms }
BootstrapCssStyles class >> controlLabel [

	^ 'control-label'
]

{ #category : #Accessing }
BootstrapCssStyles class >> date [

	^ BootstrapDatepickerConstants date
]

{ #category : #Typography }
BootstrapCssStyles class >> definitionListHorizontal [

	^ 'dl-horizontal'
]

{ #category : #Forms }
BootstrapCssStyles class >> disabled [

	^ 'disabled'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> divider [

	^ 'divider'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdown [

	^ 'dropdown'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdownBackdrop [

	^ 'dropdown-backdrop'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdownHeader [

	^ 'dropdown-header'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdownMenu [

	^ 'dropdown-menu'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdownMenuLeft [

	^ 'dropdown-menu-left'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdownMenuRight [

	^ 'dropdown-menu-right'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropdownToggle [

	^ 'dropdown-toggle'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> dropup [

	^ 'dropup'
]

{ #category : #Accessing }
BootstrapCssStyles class >> fade [

	^ 'fade'
]

{ #category : #Forms }
BootstrapCssStyles class >> formControl [

	^ 'form-control'
]

{ #category : #Forms }
BootstrapCssStyles class >> formControlStatic [

	^ 'form-control-static'
]

{ #category : #Forms }
BootstrapCssStyles class >> formGroup [

	^ 'form-group'
]

{ #category : #Forms }
BootstrapCssStyles class >> formGroupLarge [

	^ 'form-group-lg'
]

{ #category : #Forms }
BootstrapCssStyles class >> formGroupSmall [

	^ 'form-group-sm'
]

{ #category : #Forms }
BootstrapCssStyles class >> formHorizontal [

	^ 'form-horizontal'
]

{ #category : #Forms }
BootstrapCssStyles class >> formInline [

	^ 'form-inline'
]

{ #category : #Images }
BootstrapCssStyles class >> glyphicon [

	^ 'glyphicon'
]

{ #category : #Forms }
BootstrapCssStyles class >> hasError [

	^ 'has-error'
]

{ #category : #Forms }
BootstrapCssStyles class >> hasFeedback [

	^ 'has-feedback'
]

{ #category : #Forms }
BootstrapCssStyles class >> hasSuccess [

	^ 'has-success'
]

{ #category : #Forms }
BootstrapCssStyles class >> hasWarning [

	^ 'has-warning'
]

{ #category : #Forms }
BootstrapCssStyles class >> helpBlock [

	^ 'help-block'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> hidden [

	^'hidden'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> hiddenExtraSmall [

	^ 'hidden-xs'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> hiddenLarge [

	^ 'hidden-lg'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> hiddenMedium [

	^ 'hidden-md'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> hiddenPrint [

	^ 'hidden-print'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> hiddenSmall [

	^ 'hidden-sm'
]

{ #category : #Navigation }
BootstrapCssStyles class >> iconBar [

	^ 'icon-bar'
]

{ #category : #Images }
BootstrapCssStyles class >> imageCircle [

	^'img-circle'
]

{ #category : #Images }
BootstrapCssStyles class >> imageResponsive [

	^'img-responsive'
]

{ #category : #Images }
BootstrapCssStyles class >> imageRounded [

	^'img-rounded'
]

{ #category : #Images }
BootstrapCssStyles class >> imageThumbnail [

	^'img-thumbnail'
]

{ #category : #Collapse }
BootstrapCssStyles class >> in [

	^'in'
]

{ #category : #Typography }
BootstrapCssStyles class >> initialism [

	^ 'initialism'
]

{ #category : #'Input Groups' }
BootstrapCssStyles class >> inputGroup [

	^ 'input-group'
]

{ #category : #'Input Groups' }
BootstrapCssStyles class >> inputGroupAddon [

	^ 'input-group-addon'
]

{ #category : #'Input Groups' }
BootstrapCssStyles class >> inputGroupButton [

	^ 'input-group-btn'
]

{ #category : #'Input Groups' }
BootstrapCssStyles class >> inputGroupLarge [

	^ 'input-group-lg'
]

{ #category : #'Input Groups' }
BootstrapCssStyles class >> inputGroupSmall [

	^ 'input-group-sm'
]

{ #category : #Forms }
BootstrapCssStyles class >> inputLarge [

	^ 'input-lg'
]

{ #category : #Forms }
BootstrapCssStyles class >> inputSmall [

	^ 'input-sm'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> invisible [

	^'invisible'
]

{ #category : #Containers }
BootstrapCssStyles class >> jumbotron [

	^'jumbotron'
]

{ #category : #Labels }
BootstrapCssStyles class >> label [

	^ 'label'
]

{ #category : #Labels }
BootstrapCssStyles class >> labelDanger [

	^ 'label-danger'
]

{ #category : #Labels }
BootstrapCssStyles class >> labelDefault [

	^ 'label-default'
]

{ #category : #Labels }
BootstrapCssStyles class >> labelInfo [

	^ 'label-info'
]

{ #category : #Labels }
BootstrapCssStyles class >> labelPrimary [

	^ 'label-primary'
]

{ #category : #Labels }
BootstrapCssStyles class >> labelSuccess [

	^ 'label-success'
]

{ #category : #Labels }
BootstrapCssStyles class >> labelWarning [

	^ 'label-warning'
]

{ #category : #Typography }
BootstrapCssStyles class >> lead [

	^ 'lead'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroup [

	^ 'list-group'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItem [

	^ 'list-group-item'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItemDanger [

	^ 'list-group-item-danger'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItemHeading [

	^ 'list-group-item-heading'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItemInfo [

	^ 'list-group-item-info'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItemSuccess [

	^ 'list-group-item-success'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItemText [

	^ 'list-group-item-text'
]

{ #category : #'List Groups' }
BootstrapCssStyles class >> listGroupItemWarning [

	^ 'list-group-item-warning'
]

{ #category : #Typography }
BootstrapCssStyles class >> listInline [

	^ 'list-inline'
]

{ #category : #Typography }
BootstrapCssStyles class >> listUnstyled [

	^ 'list-unstyled'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> media [

	^ 'media'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaBody [

	^ 'media-body'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaHeading [

	^ 'media-heading'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaLeft [

	^ 'media-left'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaList [

	^ 'media-list'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaMiddle [

	^ 'media-middle'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaObject [

	^ 'media-object'
]

{ #category : #'Media Object' }
BootstrapCssStyles class >> mediaRight [

	^ 'media-right'
]

{ #category : #Modal }
BootstrapCssStyles class >> modal [

	^ 'modal'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalBackdrop [

	^ 'modal-backdrop'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalBody [

	^ 'modal-body'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalContent [

	^ 'modal-content'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalDialog [

	^ 'modal-dialog'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalFooter [

	^ 'modal-footer'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalHeader [

	^ 'modal-header'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalLarge [

	^ 'modal-lg'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalOpen [

	^ 'modal-open'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalSmall [

	^ 'modal-sm'
]

{ #category : #Modal }
BootstrapCssStyles class >> modalTitle [

	^ 'modal-title'
]

{ #category : #Navigation }
BootstrapCssStyles class >> nav [

	^ 'nav'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navJustified [

	^ 'nav-justified'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navPills [

	^ 'nav-pills'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navStacked [

	^ 'nav-stacked'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navTabs [

	^ 'nav-tabs'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbar [

	^ 'navbar'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarBrand [

	^ 'navbar-brand'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarButton [

	^ 'navbar-btn'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarCollapse [

	^ 'navbar-collapse'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarDefault [

	^ 'navbar-default'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarFixedBottom [

	^ 'navbar-fixed-bottom'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarFixedTop [

	^ 'navbar-fixed-top'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarForm [

	^ 'navbar-form'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarHeader [

	^ 'navbar-header'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarInverse [

	^ 'navbar-inverse'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarLeft [

	^ 'navbar-left'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarLink [

	^ 'navbar-link'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarNavigation [

	^ 'navbar-nav'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarRight [

	^ 'navbar-right'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarStaticTop [

	^ 'navbar-static-top'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarText [

	^ 'navbar-text'
]

{ #category : #Navigation }
BootstrapCssStyles class >> navbarToggle [

	^ 'navbar-toggle'
]

{ #category : #Pagination }
BootstrapCssStyles class >> next [

	^ 'next'
]

{ #category : #Dropdowns }
BootstrapCssStyles class >> open [

	^ 'open'
]

{ #category : #Containers }
BootstrapCssStyles class >> pageHeader [

	^'page-header'
]

{ #category : #Pagination }
BootstrapCssStyles class >> pager [

	^ 'pager'
]

{ #category : #Pagination }
BootstrapCssStyles class >> pagination [

	^ 'pagination'
]

{ #category : #Pagination }
BootstrapCssStyles class >> paginationLarge [

	^ 'pagination-lg'
]

{ #category : #Pagination }
BootstrapCssStyles class >> paginationSmall [

	^ 'pagination-sm'
]

{ #category : #Panels }
BootstrapCssStyles class >> panel [

	^ 'panel'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelBody [

	^ 'panel-body'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelCollapse [

	^ 'panel-collapse'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelDanger [

	^ 'panel-danger'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelDefault [

	^ 'panel-default'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelFooter [

	^ 'panel-footer'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelGroup [

	^ 'panel-group'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelHeading [

	^ 'panel-heading'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelInfo [

	^ 'panel-info'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelPrimary [

	^ 'panel-primary'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelSuccess [

	^ 'panel-success'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelTitle [

	^ 'panel-title'
]

{ #category : #Panels }
BootstrapCssStyles class >> panelWarning [

	^ 'panel-warning'
]

{ #category : #Popover }
BootstrapCssStyles class >> popover [

	^ 'popover'
]

{ #category : #Popover }
BootstrapCssStyles class >> popoverContent [

	^ 'popover-content'
]

{ #category : #Popover }
BootstrapCssStyles class >> popoverTitle [

	^ 'popover-title'
]

{ #category : #Code }
BootstrapCssStyles class >> preScrollable [

	^ 'pre-scrollable'
]

{ #category : #Pagination }
BootstrapCssStyles class >> previous [

	^ 'previous'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progress [

	^ 'progress'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progressBar [

	^ 'progress-bar'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progressBarDanger [

	^ 'progress-bar-danger'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progressBarInfo [

	^ 'progress-bar-info'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progressBarStriped [

	^ 'progress-bar-striped'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progressBarSuccess [

	^ 'progress-bar-success'
]

{ #category : #'Progress Bars' }
BootstrapCssStyles class >> progressBarWarning [

	^ 'progress-bar-warning'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> pullLeft [

	^ 'pull-left'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> pullRight [

	^ 'pull-right'
]

{ #category : #Forms }
BootstrapCssStyles class >> radio [

	^ 'radio'
]

{ #category : #Forms }
BootstrapCssStyles class >> radioInline [

	^ 'radio-inline'
]

{ #category : #'Grid System' }
BootstrapCssStyles class >> row [

	^'row'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> screenReaderOnly [

	^'sr-only'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> screenReaderOnlyFocusable [

	^'sr-only-focusable'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> show [

	^'show'
]

{ #category : #Typography }
BootstrapCssStyles class >> small [

	^ 'small'
]

{ #category : #Navigation }
BootstrapCssStyles class >> tabContent [

	^ 'tab-content'
]

{ #category : #Navigation }
BootstrapCssStyles class >> tabPane [

	^ 'tab-pane'
]

{ #category : #Tables }
BootstrapCssStyles class >> table [

	^ 'table'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableBordered [

	^ 'table-bordered'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableCondensed [

	^ 'table-condensed'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableDanger [

	^ 'danger'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableHover [

	^ 'table-hover'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableInfo [

	^ 'info'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableResponsive [

	^ 'table-responsive'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableStriped [

	^ 'table-striped'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableSuccess [

	^ 'success'
]

{ #category : #Tables }
BootstrapCssStyles class >> tableWarning [

	^ 'warning'
]

{ #category : #Typography }
BootstrapCssStyles class >> textCapitalize [

	^ 'text-capitalize'
]

{ #category : #Typography }
BootstrapCssStyles class >> textCenter [

	^ 'text-center'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textDanger [

	^ 'text-danger'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textHide [

	^'text-hide'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textInfo [

	^ 'text-info'
]

{ #category : #Typography }
BootstrapCssStyles class >> textJustify [

	^ 'text-justify'
]

{ #category : #Typography }
BootstrapCssStyles class >> textLeft [

	^ 'text-left'
]

{ #category : #Typography }
BootstrapCssStyles class >> textLowercase [

	^ 'text-lowercase'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textMuted [

	^ 'text-muted'
]

{ #category : #Typography }
BootstrapCssStyles class >> textNowrap [

	^ 'text-nowrap'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textPrimary [

	^ 'text-primary'
]

{ #category : #Typography }
BootstrapCssStyles class >> textRight [

	^ 'text-right'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textSuccess [

	^ 'text-success'
]

{ #category : #Typography }
BootstrapCssStyles class >> textUppercase [

	^ 'text-uppercase'
]

{ #category : #'Helper Classes' }
BootstrapCssStyles class >> textWarning [

	^ 'text-warning'
]

{ #category : #Containers }
BootstrapCssStyles class >> thumbnail [

	^'thumbnail'
]

{ #category : #Tooltips }
BootstrapCssStyles class >> tooltip [

	^ 'tooltip'
]

{ #category : #Tooltips }
BootstrapCssStyles class >> tooltipArrow [

	^ 'tooltip-arrow'
]

{ #category : #Tooltips }
BootstrapCssStyles class >> tooltipInner [

	^ 'tooltip-inner'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleExtraSmallBlock [

	^ 'visible-xs-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleExtraSmallInline [

	^ 'visible-xs-inline'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleExtraSmallInlineBlock [

	^ 'visible-xs-inline-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleLargeBlock [

	^ 'visible-lg-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleLargeInline [

	^ 'visible-lg-inline'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleLargeInlineBlock [

	^ 'visible-lg-inline-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleMediumBlock [

	^ 'visible-md-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleMediumInline [

	^ 'visible-md-inline'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleMediumInlineBlock [

	^ 'visible-md-inline-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visiblePrintBlock [

	^ 'visible-print-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visiblePrintInline [

	^ 'visible-print-inline'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visiblePrintInlineBlock [

	^ 'visible-print-inline-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleSmallBlock [

	^ 'visible-sm-block'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleSmallInline [

	^ 'visible-sm-inline'
]

{ #category : #'Responsive Utilities' }
BootstrapCssStyles class >> visibleSmallInlineBlock [

	^ 'visible-sm-inline-block'
]

{ #category : #Wells }
BootstrapCssStyles class >> well [

	^ 'well'
]

{ #category : #Wells }
BootstrapCssStyles class >> wellLarge [

	^ 'well-lg'
]

{ #category : #Wells }
BootstrapCssStyles class >> wellSmall [

	^ 'well-sm'
]
