"
This class provides access to several constants
"
Class {
	#name : #BootstrapSelectConstants,
	#superclass : #Object,
	#category : #'Willow-Bootstrap-Select'
}

{ #category : #'Data-API' }
BootstrapSelectConstants class >> actionsBox [

	^ 'actions-box'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> auto [

	^ 'auto'
]

{ #category : #'Accessing - Classes' }
BootstrapSelectConstants class >> bootstrapSelect [

	^'bootstrap-select'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> changedSelect [

	^ 'changed.bs.select'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> container [

	^ 'container'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> contains [

	^ 'contains'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> count [

	^ 'count'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> countAfter: anInteger [

	^ 'count > <1p>' expandMacrosWith: anInteger
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> countSelectedText [

	^ 'count-selected-text'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> deselectAllText [

	^ 'deselect-all-text'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> dropdownAlignRight [

	^ 'dropdown-align-right'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> dropupAuto [

	^ 'dropup-auto'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> fit [

	^ 'fit'


]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> header [

	^ 'header'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> hiddenSelect [

	^ 'hidden.bs.select'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> hideDisabled [

	^ 'hide-disabled'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> hideSelect [

	^ 'hide.bs.select'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> iconBase [

	^ 'icon-base'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> liveSearch [

	^ 'live-search'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> liveSearchNormalize [

	^ 'live-search-normalize'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> liveSearchPlaceholder [

	^ 'live-search-placeholder'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> liveSearchStyle [

	^ 'live-search-style'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> loadedSelect [

	^ 'loaded.bs.select'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> maxOptions [

	^ 'max-options'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> maxOptionsText [

	^ 'max-options-text'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> mobile [

	^ 'mobile'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> multipleSeparator [

	^ 'multiple-separator'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> noneSelectedText [

	^'none-selected-text'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> refreshedSelect [

	^ 'refreshed.bs.select'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> renderedSelect [

	^ 'rendered.bs.select'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> selectAllText [

	^ 'select-all-text'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> selectOnTab [

	^ 'select-on-tab'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> selectedTextFormat [

	^'selected-text-format'
]

{ #category : #'Accessing - Classes' }
BootstrapSelectConstants class >> selectpicker [

	^'selectpicker'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> showContent [

	^ 'show-content'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> showIcon [

	^ 'show-icon'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> showSelect [

	^ 'show.bs.select'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> showSubtext [

	^ 'show-subtext'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> showTick [

	^ 'show-tick'
]

{ #category : #'Accessing -Events' }
BootstrapSelectConstants class >> shownSelect [

	^ 'shown.bs.select'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> startsWith [

	^ 'startsWith'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> static [

	^ 'static'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> style [

	^ 'style'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> tickIcon [

	^ 'tick-icon'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> title [

	^ 'title'
]

{ #category : #Accessing }
BootstrapSelectConstants class >> values [

	^ 'values'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> width [

	^'width'
]

{ #category : #'Data-API' }
BootstrapSelectConstants class >> windowPadding [

	^ 'window-padding'
]
