Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> active [

	^ self commandStyledWith: styleProviderBinding content active
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alert [

	^ self commandStyledWith: styleProviderBinding content alert
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertDanger [

	^ self commandStyledWith: styleProviderBinding content alertDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertDismissible [

	^ self commandStyledWith: styleProviderBinding content alertDismissible
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertInfo [

	^ self commandStyledWith: styleProviderBinding content alertInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertLink [

	^ self commandStyledWith: styleProviderBinding content alertLink
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertSuccess [

	^ self commandStyledWith: styleProviderBinding content alertSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertWarning [

	^ self commandStyledWith: styleProviderBinding content alertWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> arrow [

	^ self commandStyledWith: styleProviderBinding content arrow
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundDanger [

	^ self commandStyledWith: styleProviderBinding content backgroundDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundInfo [

	^ self commandStyledWith: styleProviderBinding content backgroundInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundPrimary [

	^ self commandStyledWith: styleProviderBinding content backgroundPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundSuccess [

	^ self commandStyledWith: styleProviderBinding content backgroundSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundWarning [

	^ self commandStyledWith: styleProviderBinding content backgroundWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> badge [

	^ self commandStyledWith: styleProviderBinding content badge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> blockquoteReverse [

	^ self commandStyledWith: styleProviderBinding content blockquoteReverse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> bootstrap [

	styleProviderBinding := Binding to: BootstrapCssStyles
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> breadcrumb [

	^ self commandStyledWith: styleProviderBinding content breadcrumb
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> button [

	^ self commandStyledWith: styleProviderBinding content button
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonBlock [

	^ self commandStyledWith: styleProviderBinding content buttonBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonDanger [

	^ self commandStyledWith: styleProviderBinding content buttonDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonDefault [

	^ self commandStyledWith: styleProviderBinding content buttonDefault
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonExtraSmall [

	^ self commandStyledWith: styleProviderBinding content buttonExtraSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroup [

	^ self commandStyledWith: styleProviderBinding content buttonGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupExtraSmall [

	^ self commandStyledWith: styleProviderBinding content buttonGroupExtraSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupJustified [

	^ self commandStyledWith: styleProviderBinding content buttonGroupJustified
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupLarge [

	^ self commandStyledWith: styleProviderBinding content buttonGroupLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupSmall [

	^ self commandStyledWith: styleProviderBinding content buttonGroupSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupVertical [

	^ self commandStyledWith: styleProviderBinding content buttonGroupVertical
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonInfo [

	^ self commandStyledWith: styleProviderBinding content buttonInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonLarge [

	^ self commandStyledWith: styleProviderBinding content buttonLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonLink [

	^ self commandStyledWith: styleProviderBinding content buttonLink
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonPrimary [

	^ self commandStyledWith: styleProviderBinding content buttonPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonSmall [

	^ self commandStyledWith: styleProviderBinding content buttonSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonSuccess [

	^ self commandStyledWith: styleProviderBinding content buttonSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonToolbar [

	^ self commandStyledWith: styleProviderBinding content buttonToolbar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonWarning [

	^ self commandStyledWith: styleProviderBinding content buttonWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> caret [

	^ self commandStyledWith: styleProviderBinding content caret
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> centerBlock [

	^ self commandStyledWith: styleProviderBinding content centerBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> checkbox [

	^ self commandStyledWith: styleProviderBinding content checkbox
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> checkboxInline [

	^ self commandStyledWith: styleProviderBinding content checkboxInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> clearfix [

	^ self commandStyledWith: styleProviderBinding content clearfix
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> close [

	^ self commandStyledWith: styleProviderBinding content close
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> collapse [

	^ self commandStyledWith: styleProviderBinding content collapse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> collapsed [

	^ self commandStyledWith: styleProviderBinding content collapsed
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> collapsing [

	^ self commandStyledWith: styleProviderBinding content collapsing
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnExtraSmall: count [

	^ self commandStyledWith: ( styleProviderBinding content columnExtraSmall: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnExtraSmallOffset: count [

	^ self commandStyledWith: ( styleProviderBinding content columnExtraSmallOffset: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnExtraSmallPull: count [

	^ self commandStyledWith: ( styleProviderBinding content columnExtraSmallPull: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnExtraSmallPush: count [

	^ self commandStyledWith: ( styleProviderBinding content columnExtraSmallPush: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnLarge: count [

	^ self commandStyledWith: ( styleProviderBinding content columnLarge: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnLargeOffset: count [

	^ self commandStyledWith: ( styleProviderBinding content columnLargeOffset: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnLargePull: count [

	^ self commandStyledWith: ( styleProviderBinding content columnLargePull: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnLargePush: count [

	^ self commandStyledWith: ( styleProviderBinding content columnLargePush: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnMedium: count [

	^ self commandStyledWith: ( styleProviderBinding content columnMedium: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnMediumOffset: count [

	^ self commandStyledWith: ( styleProviderBinding content columnMediumOffset: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnMediumPull: count [

	^ self commandStyledWith: ( styleProviderBinding content columnMediumPull: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnMediumPush: count [

	^ self commandStyledWith: ( styleProviderBinding content columnMediumPush: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnSmall: count [

	^ self commandStyledWith: ( styleProviderBinding content columnSmall: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnSmallOffset: count [

	^ self commandStyledWith: ( styleProviderBinding content columnSmallOffset: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnSmallPull: count [

	^ self commandStyledWith: ( styleProviderBinding content columnSmallPull: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnSmallPush: count [

	^ self commandStyledWith: ( styleProviderBinding content columnSmallPush: count )
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> container [

	^ self commandStyledWith: styleProviderBinding content container
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> containerFluid [

	^ self commandStyledWith: styleProviderBinding content containerFluid
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> controlLabel [

	^ self commandStyledWith: styleProviderBinding content controlLabel
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> date [

	^ self commandStyledWith: styleProviderBinding content date
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> definitionListHorizontal [

	^ self commandStyledWith: styleProviderBinding content definitionListHorizontal
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> disabled [

	^ self commandStyledWith: styleProviderBinding content disabled
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> divider [

	^ self commandStyledWith: styleProviderBinding content divider
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdown [

	^ self commandStyledWith: styleProviderBinding content dropdown
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownBackdrop [

	^ self commandStyledWith: styleProviderBinding content dropdownBackdrop
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownHeader [

	^ self commandStyledWith: styleProviderBinding content dropdownHeader
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownMenu [

	^ self commandStyledWith: styleProviderBinding content dropdownMenu
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownMenuLeft [

	^ self commandStyledWith: styleProviderBinding content dropdownMenuLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownMenuRight [

	^ self commandStyledWith: styleProviderBinding content dropdownMenuRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownToggle [

	^ self commandStyledWith: styleProviderBinding content dropdownToggle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropup [

	^ self commandStyledWith: styleProviderBinding content dropup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> fade [

	^ self commandStyledWith: styleProviderBinding content fade
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formControl [

	^ self commandStyledWith: styleProviderBinding content formControl
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formControlStatic [

	^ self commandStyledWith: styleProviderBinding content formControlStatic
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formGroup [

	^ self commandStyledWith: styleProviderBinding content formGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formGroupLarge [

	^ self commandStyledWith: styleProviderBinding content formGroupLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formGroupSmall [

	^ self commandStyledWith: styleProviderBinding content formGroupSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formHorizontal [

	^ self commandStyledWith: styleProviderBinding content formHorizontal
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formInline [

	^ self commandStyledWith: styleProviderBinding content formInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> glyphicon [

	^ self commandStyledWith: styleProviderBinding content glyphicon
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hasError [

	^ self commandStyledWith: styleProviderBinding content hasError
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hasFeedback [

	^ self commandStyledWith: styleProviderBinding content hasFeedback
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hasSuccess [

	^ self commandStyledWith: styleProviderBinding content hasSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hasWarning [

	^ self commandStyledWith: styleProviderBinding content hasWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> helpBlock [

	^ self commandStyledWith: styleProviderBinding content helpBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hidden [

	^ self commandStyledWith: styleProviderBinding content hidden
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hiddenExtraSmall [

	^ self commandStyledWith: styleProviderBinding content hiddenExtraSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hiddenLarge [

	^ self commandStyledWith: styleProviderBinding content hiddenLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hiddenMedium [

	^ self commandStyledWith: styleProviderBinding content hiddenMedium
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hiddenPrint [

	^ self commandStyledWith: styleProviderBinding content hiddenPrint
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> hiddenSmall [

	^ self commandStyledWith: styleProviderBinding content hiddenSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> iconBar [

	^ self commandStyledWith: styleProviderBinding content iconBar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> imageCircle [

	^ self commandStyledWith: styleProviderBinding content imageCircle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> imageResponsive [

	^ self commandStyledWith: styleProviderBinding content imageResponsive
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> imageRounded [

	^ self commandStyledWith: styleProviderBinding content imageRounded
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> imageThumbnail [

	^ self commandStyledWith: styleProviderBinding content imageThumbnail
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> in [

	^ self commandStyledWith: styleProviderBinding content in
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> initialism [

	^ self commandStyledWith: styleProviderBinding content initialism
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroup [

	^ self commandStyledWith: styleProviderBinding content inputGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroupAddon [

	^ self commandStyledWith: styleProviderBinding content inputGroupAddon
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroupButton [

	^ self commandStyledWith: styleProviderBinding content inputGroupButton
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroupLarge [

	^ self commandStyledWith: styleProviderBinding content inputGroupLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroupSmall [

	^ self commandStyledWith: styleProviderBinding content inputGroupSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputLarge [

	^ self commandStyledWith: styleProviderBinding content inputLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputSmall [

	^ self commandStyledWith: styleProviderBinding content inputSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> invisible [

	^ self commandStyledWith: styleProviderBinding content invisible
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> jumbotron [

	^ self commandStyledWith: styleProviderBinding content jumbotron
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> label [

	^ self commandStyledWith: styleProviderBinding content label
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> labelDanger [

	^ self commandStyledWith: styleProviderBinding content labelDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> labelDefault [

	^ self commandStyledWith: styleProviderBinding content labelDefault
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> labelInfo [

	^ self commandStyledWith: styleProviderBinding content labelInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> labelPrimary [

	^ self commandStyledWith: styleProviderBinding content labelPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> labelSuccess [

	^ self commandStyledWith: styleProviderBinding content labelSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> labelWarning [

	^ self commandStyledWith: styleProviderBinding content labelWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> lead [

	^ self commandStyledWith: styleProviderBinding content lead
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroup [

	^ self commandStyledWith: styleProviderBinding content listGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItem [

	^ self commandStyledWith: styleProviderBinding content listGroupItem
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemDanger [

	^ self commandStyledWith: styleProviderBinding content listGroupItemDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemHeading [

	^ self commandStyledWith: styleProviderBinding content listGroupItemHeading
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemInfo [

	^ self commandStyledWith: styleProviderBinding content listGroupItemInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemSuccess [

	^ self commandStyledWith: styleProviderBinding content listGroupItemSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemText [

	^ self commandStyledWith: styleProviderBinding content listGroupItemText
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemWarning [

	^ self commandStyledWith: styleProviderBinding content listGroupItemWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listInline [

	^ self commandStyledWith: styleProviderBinding content listInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listUnstyled [

	^ self commandStyledWith: styleProviderBinding content listUnstyled
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> media [

	^ self commandStyledWith: styleProviderBinding content media
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaBody [

	^ self commandStyledWith: styleProviderBinding content mediaBody
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaHeading [

	^ self commandStyledWith: styleProviderBinding content mediaHeading
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaLeft [

	^ self commandStyledWith: styleProviderBinding content mediaLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaList [

	^ self commandStyledWith: styleProviderBinding content mediaList
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaMiddle [

	^ self commandStyledWith: styleProviderBinding content mediaMiddle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaObject [

	^ self commandStyledWith: styleProviderBinding content mediaObject
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaRight [

	^ self commandStyledWith: styleProviderBinding content mediaRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modal [

	^ self commandStyledWith: styleProviderBinding content modal
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalBackdrop [

	^ self commandStyledWith: styleProviderBinding content modalBackdrop
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalBody [

	^ self commandStyledWith: styleProviderBinding content modalBody
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalContent [

	^ self commandStyledWith: styleProviderBinding content modalContent
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalDialog [

	^ self commandStyledWith: styleProviderBinding content modalDialog
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalFooter [

	^ self commandStyledWith: styleProviderBinding content modalFooter
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalHeader [

	^ self commandStyledWith: styleProviderBinding content modalHeader
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalLarge [

	^ self commandStyledWith: styleProviderBinding content modalLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalOpen [

	^ self commandStyledWith: styleProviderBinding content modalOpen
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalSmall [

	^ self commandStyledWith: styleProviderBinding content modalSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalTitle [

	^ self commandStyledWith: styleProviderBinding content modalTitle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> nav [

	^ self commandStyledWith: styleProviderBinding content nav
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navJustified [

	^ self commandStyledWith: styleProviderBinding content navJustified
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navPills [

	^ self commandStyledWith: styleProviderBinding content navPills
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navStacked [

	^ self commandStyledWith: styleProviderBinding content navStacked
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navTabs [

	^ self commandStyledWith: styleProviderBinding content navTabs
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbar [

	^ self commandStyledWith: styleProviderBinding content navbar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarBrand [

	^ self commandStyledWith: styleProviderBinding content navbarBrand
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarButton [

	^ self commandStyledWith: styleProviderBinding content navbarButton
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarCollapse [

	^ self commandStyledWith: styleProviderBinding content navbarCollapse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarDefault [

	^ self commandStyledWith: styleProviderBinding content navbarDefault
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarFixedBottom [

	^ self commandStyledWith: styleProviderBinding content navbarFixedBottom
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarFixedTop [

	^ self commandStyledWith: styleProviderBinding content navbarFixedTop
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarForm [

	^ self commandStyledWith: styleProviderBinding content navbarForm
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarHeader [

	^ self commandStyledWith: styleProviderBinding content navbarHeader
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarInverse [

	^ self commandStyledWith: styleProviderBinding content navbarInverse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarLeft [

	^ self commandStyledWith: styleProviderBinding content navbarLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarLink [

	^ self commandStyledWith: styleProviderBinding content navbarLink
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarNavigation [

	^ self commandStyledWith: styleProviderBinding content navbarNavigation
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarRight [

	^ self commandStyledWith: styleProviderBinding content navbarRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarStaticTop [

	^ self commandStyledWith: styleProviderBinding content navbarStaticTop
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarText [

	^ self commandStyledWith: styleProviderBinding content navbarText
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarToggle [

	^ self commandStyledWith: styleProviderBinding content navbarToggle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> next [

	^ self commandStyledWith: styleProviderBinding content next
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> open [

	^ self commandStyledWith: styleProviderBinding content open
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> pageHeader [

	^ self commandStyledWith: styleProviderBinding content pageHeader
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> pager [

	^ self commandStyledWith: styleProviderBinding content pager
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> pagination [

	^ self commandStyledWith: styleProviderBinding content pagination
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> paginationLarge [

	^ self commandStyledWith: styleProviderBinding content paginationLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> paginationSmall [

	^ self commandStyledWith: styleProviderBinding content paginationSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panel [

	^ self commandStyledWith: styleProviderBinding content panel
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelBody [

	^ self commandStyledWith: styleProviderBinding content panelBody
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelCollapse [

	^ self commandStyledWith: styleProviderBinding content panelCollapse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelDanger [

	^ self commandStyledWith: styleProviderBinding content panelDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelDefault [

	^ self commandStyledWith: styleProviderBinding content panelDefault
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelFooter [

	^ self commandStyledWith: styleProviderBinding content panelFooter
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelGroup [

	^ self commandStyledWith: styleProviderBinding content panelGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelHeading [

	^ self commandStyledWith: styleProviderBinding content panelHeading
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelInfo [

	^ self commandStyledWith: styleProviderBinding content panelInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelPrimary [

	^ self commandStyledWith: styleProviderBinding content panelPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelSuccess [

	^ self commandStyledWith: styleProviderBinding content panelSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelTitle [

	^ self commandStyledWith: styleProviderBinding content panelTitle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> panelWarning [

	^ self commandStyledWith: styleProviderBinding content panelWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> popover [

	^ self commandStyledWith: styleProviderBinding content popover
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> popoverContent [

	^ self commandStyledWith: styleProviderBinding content popoverContent
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> popoverTitle [

	^ self commandStyledWith: styleProviderBinding content popoverTitle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> preScrollable [

	^ self commandStyledWith: styleProviderBinding content preScrollable
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> previous [

	^ self commandStyledWith: styleProviderBinding content previous
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progress [

	^ self commandStyledWith: styleProviderBinding content progress
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBar [

	^ self commandStyledWith: styleProviderBinding content progressBar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBarDanger [

	^ self commandStyledWith: styleProviderBinding content progressBarDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBarInfo [

	^ self commandStyledWith: styleProviderBinding content progressBarInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBarStriped [

	^ self commandStyledWith: styleProviderBinding content progressBarStriped
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBarSuccess [

	^ self commandStyledWith: styleProviderBinding content progressBarSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBarWarning [

	^ self commandStyledWith: styleProviderBinding content progressBarWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> pullLeft [

	^ self commandStyledWith: styleProviderBinding content pullLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> pullRight [

	^ self commandStyledWith: styleProviderBinding content pullRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> radio [

	^ self commandStyledWith: styleProviderBinding content radio
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> radioInline [

	^ self commandStyledWith: styleProviderBinding content radioInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> row [

	^ self commandStyledWith: styleProviderBinding content row
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> screenReaderOnly [

	^ self commandStyledWith: styleProviderBinding content screenReaderOnly
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> screenReaderOnlyFocusable [

	^ self commandStyledWith: styleProviderBinding content screenReaderOnlyFocusable
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> show [

	^ self commandStyledWith: styleProviderBinding content show
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> small [

	^ self commandStyledWith: styleProviderBinding content small
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tabContent [

	^ self commandStyledWith: styleProviderBinding content tabContent
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tabPane [

	^ self commandStyledWith: styleProviderBinding content tabPane
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> table [

	^ self commandStyledWith: styleProviderBinding content table
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableBordered [

	^ self commandStyledWith: styleProviderBinding content tableBordered
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableCondensed [

	^ self commandStyledWith: styleProviderBinding content tableCondensed
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableDanger [

	^ self commandStyledWith: styleProviderBinding content tableDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableHover [

	^ self commandStyledWith: styleProviderBinding content tableHover
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableInfo [

	^ self commandStyledWith: styleProviderBinding content tableInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableResponsive [

	^ self commandStyledWith: styleProviderBinding content tableResponsive
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableStriped [

	^ self commandStyledWith: styleProviderBinding content tableStriped
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableSuccess [

	^ self commandStyledWith: styleProviderBinding content tableSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableWarning [

	^ self commandStyledWith: styleProviderBinding content tableWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textCapitalize [

	^ self commandStyledWith: styleProviderBinding content textCapitalize
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textCenter [

	^ self commandStyledWith: styleProviderBinding content textCenter
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textDanger [

	^ self commandStyledWith: styleProviderBinding content textDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textHide [

	^ self commandStyledWith: styleProviderBinding content textHide
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textInfo [

	^ self commandStyledWith: styleProviderBinding content textInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textJustify [

	^ self commandStyledWith: styleProviderBinding content textJustify
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textLeft [

	^ self commandStyledWith: styleProviderBinding content textLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textLowercase [

	^ self commandStyledWith: styleProviderBinding content textLowercase
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textMuted [

	^ self commandStyledWith: styleProviderBinding content textMuted
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textNowrap [

	^ self commandStyledWith: styleProviderBinding content textNowrap
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textPrimary [

	^ self commandStyledWith: styleProviderBinding content textPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textRight [

	^ self commandStyledWith: styleProviderBinding content textRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textSuccess [

	^ self commandStyledWith: styleProviderBinding content textSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textUppercase [

	^ self commandStyledWith: styleProviderBinding content textUppercase
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textWarning [

	^ self commandStyledWith: styleProviderBinding content textWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> thumbnail [

	^ self commandStyledWith: styleProviderBinding content thumbnail
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tooltip [

	^ self commandStyledWith: styleProviderBinding content tooltip
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tooltipArrow [

	^ self commandStyledWith: styleProviderBinding content tooltipArrow
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tooltipInner [

	^ self commandStyledWith: styleProviderBinding content tooltipInner
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleExtraSmallBlock [

	^ self commandStyledWith: styleProviderBinding content visibleExtraSmallBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleExtraSmallInline [

	^ self commandStyledWith: styleProviderBinding content visibleExtraSmallInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleExtraSmallInlineBlock [

	^ self commandStyledWith: styleProviderBinding content visibleExtraSmallInlineBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleLargeBlock [

	^ self commandStyledWith: styleProviderBinding content visibleLargeBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleLargeInline [

	^ self commandStyledWith: styleProviderBinding content visibleLargeInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleLargeInlineBlock [

	^ self commandStyledWith: styleProviderBinding content visibleLargeInlineBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleMediumBlock [

	^ self commandStyledWith: styleProviderBinding content visibleMediumBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleMediumInline [

	^ self commandStyledWith: styleProviderBinding content visibleMediumInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleMediumInlineBlock [

	^ self commandStyledWith: styleProviderBinding content visibleMediumInlineBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visiblePrintBlock [

	^ self commandStyledWith: styleProviderBinding content visiblePrintBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visiblePrintInline [

	^ self commandStyledWith: styleProviderBinding content visiblePrintInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visiblePrintInlineBlock [

	^ self commandStyledWith: styleProviderBinding content visiblePrintInlineBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleSmallBlock [

	^ self commandStyledWith: styleProviderBinding content visibleSmallBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleSmallInline [

	^ self commandStyledWith: styleProviderBinding content visibleSmallInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> visibleSmallInlineBlock [

	^ self commandStyledWith: styleProviderBinding content visibleSmallInlineBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> well [

	^ self commandStyledWith: styleProviderBinding content well
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> wellLarge [

	^ self commandStyledWith: styleProviderBinding content wellLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> wellSmall [

	^ self commandStyledWith: styleProviderBinding content wellSmall
]
