Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> active [

	^ self commandStyledWith: #active
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alert [

	^ self commandStyledWith: #alert
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertDanger [

	^ self commandStyledWith: #alertDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertDismissible [

	^ self commandStyledWith: #alertDismissible
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertInfo [

	^ self commandStyledWith: #alertInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertLink [

	^ self commandStyledWith: #alertLink
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertSuccess [

	^ self commandStyledWith: #alertSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> alertWarning [

	^ self commandStyledWith: #alertWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> arrow [

	^ self commandStyledWith: #arrow
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundDanger [

	^ self commandStyledWith: #backgroundDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundInfo [

	^ self commandStyledWith: #backgroundInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundPrimary [

	^ self commandStyledWith: #backgroundPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundSuccess [

	^ self commandStyledWith: #backgroundSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> backgroundWarning [

	^ self commandStyledWith: #backgroundWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> badge [

	^ self commandStyledWith: #badge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> bootstrapCommon [

	classificationNamespace := classificationNamespace >> #bootstrapCommon
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> bootstrapSelect [

	^ self commandStyledWith: #bootstrapSelect
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> breadcrumb [

	^ self commandStyledWith: #breadcrumb
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> button [

	^ self commandStyledWith: #button
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonBlock [

	^ self commandStyledWith: #buttonBlock
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonDanger [

	^ self commandStyledWith: #buttonDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroup [

	^ self commandStyledWith: #buttonGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupLarge [

	^ self commandStyledWith: #buttonGroupLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupSmall [

	^ self commandStyledWith: #buttonGroupSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonGroupVertical [

	^ self commandStyledWith: #buttonGroupVertical
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonInfo [

	^ self commandStyledWith: #buttonInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonLarge [

	^ self commandStyledWith: #buttonLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonLink [

	^ self commandStyledWith: #buttonLink
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonPrimary [

	^ self commandStyledWith: #buttonPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonSmall [

	^ self commandStyledWith: #buttonSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonSuccess [

	^ self commandStyledWith: #buttonSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonToolbar [

	^ self commandStyledWith: #buttonToolbar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> buttonWarning [

	^ self commandStyledWith: #buttonWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> clearfix [

	^ self commandStyledWith: #clearfix
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> close [

	^ self commandStyledWith: #close
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> collapse [

	^ self commandStyledWith: #collapse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> collapsing [

	^ self commandStyledWith: #collapsing
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnExtraSmall: count [

	^ self commandStyledWith: (#'columnExtraSmall<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnLarge: count [

	^ self commandStyledWith: (#'columnLarge<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnLargeOffset: count [

	^ self commandStyledWith: (#'columnLargeOffset<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnMedium: count [

	^ self commandStyledWith: (#'columnMedium<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnMediumOffset: count [

	^ self commandStyledWith: (#'columnMediumOffset<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnSmall: count [

	^ self commandStyledWith: (#'columnSmall<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> columnSmallOffset: count [

	^ self commandStyledWith: (#'columnSmallOffset<1p>' expandMacrosWith: count)
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> container [

	^ self commandStyledWith: #container
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> containerFluid [

	^ self commandStyledWith: #containerFluid
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> disabled [

	^ self commandStyledWith: #disabled
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdown [

	^ self commandStyledWith: #dropdown
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownHeader [

	^ self commandStyledWith: #dropdownHeader
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownMenu [

	^ self commandStyledWith: #dropdownMenu
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownMenuLeft [

	^ self commandStyledWith: #dropdownMenuLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownMenuRight [

	^ self commandStyledWith: #dropdownMenuRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropdownToggle [

	^ self commandStyledWith: #dropdownToggle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> dropup [

	^ self commandStyledWith: #dropup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> fade [

	^ self commandStyledWith: #fade
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formControl [

	^ self commandStyledWith: #formControl
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formGroup [

	^ self commandStyledWith: #formGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> formInline [

	^ self commandStyledWith: #formInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> imageThumbnail [

	^ self commandStyledWith: #imageThumbnail
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> initialism [

	^ self commandStyledWith: #initialism
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroup [

	^ self commandStyledWith: #inputGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroupLarge [

	^ self commandStyledWith: #inputGroupLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> inputGroupSmall [

	^ self commandStyledWith: #inputGroupSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> invisible [

	^ self commandStyledWith: #invisible
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> jumbotron [

	^ self commandStyledWith: #jumbotron
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> lead [

	^ self commandStyledWith: #lead
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroup [

	^ self commandStyledWith: #listGroup
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItem [

	^ self commandStyledWith: #listGroupItem
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemDanger [

	^ self commandStyledWith: #listGroupItemDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemInfo [

	^ self commandStyledWith: #listGroupItemInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemSuccess [

	^ self commandStyledWith: #listGroupItemSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listGroupItemWarning [

	^ self commandStyledWith: #listGroupItemWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listInline [

	^ self commandStyledWith: #listInline
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> listUnstyled [

	^ self commandStyledWith: #listUnstyled
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> media [

	^ self commandStyledWith: #media
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> mediaBody [

	^ self commandStyledWith: #mediaBody
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modal [

	^ self commandStyledWith: #modal
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalBackdrop [

	^ self commandStyledWith: #modalBackdrop
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalBody [

	^ self commandStyledWith: #modalBody
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalContent [

	^ self commandStyledWith: #modalContent
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalDialog [

	^ self commandStyledWith: #modalDialog
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalFooter [

	^ self commandStyledWith: #modalFooter
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalHeader [

	^ self commandStyledWith: #modalHeader
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalLarge [

	^ self commandStyledWith: #modalLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalOpen [

	^ self commandStyledWith: #modalOpen
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalSmall [

	^ self commandStyledWith: #modalSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> modalTitle [

	^ self commandStyledWith: #modalTitle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> nav [

	^ self commandStyledWith: #nav
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navJustified [

	^ self commandStyledWith: #navJustified
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navPills [

	^ self commandStyledWith: #navPills
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navTabs [

	^ self commandStyledWith: #navTabs
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbar [

	^ self commandStyledWith: #navbar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarBrand [

	^ self commandStyledWith: #navbarBrand
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarCollapse [

	^ self commandStyledWith: #navbarCollapse
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarNavigation [

	^ self commandStyledWith: #navbarNavigation
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> navbarText [

	^ self commandStyledWith: #navbarText
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> pagination [

	^ self commandStyledWith: #pagination
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> paginationLarge [

	^ self commandStyledWith: #paginationLarge
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> paginationSmall [

	^ self commandStyledWith: #paginationSmall
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> popover [

	^ self commandStyledWith: #popover
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> popoverContent [

	^ self commandStyledWith: #popoverContent
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> popoverTitle [

	^ self commandStyledWith: #popoverTitle
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> preScrollable [

	^ self commandStyledWith: #preScrollable
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> previous [

	^ self commandStyledWith: #previous
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progress [

	^ self commandStyledWith: #progress
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBar [

	^ self commandStyledWith: #progressBar
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> progressBarStriped [

	^ self commandStyledWith: #progressBarStriped
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> row [

	^ self commandStyledWith: #row
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> screenReaderOnly [

	^ self commandStyledWith: #screenReaderOnly
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> screenReaderOnlyFocusable [

	^ self commandStyledWith: #screenReaderOnlyFocusable
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> selectpicker [

	^ self commandStyledWith: #selectpicker
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tabContent [

	^ self commandStyledWith: #tabContent
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tabPane [

	^ self commandStyledWith: #tabPane
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> table [

	^ self commandStyledWith: #table
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableBordered [

	^ self commandStyledWith: #tableBordered
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableDanger [

	^ self commandStyledWith: #tableDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableHover [

	^ self commandStyledWith: #tableHover
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableInfo [

	^ self commandStyledWith: #tableInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableResponsive [

	^ self commandStyledWith: #tableResponsive
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableStriped [

	^ self commandStyledWith: #tableStriped
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableSuccess [

	^ self commandStyledWith: #tableSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tableWarning [

	^ self commandStyledWith: #tableWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textCapitalize [

	^ self commandStyledWith: #textCapitalize
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textCenter [

	^ self commandStyledWith: #textCenter
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textDanger [

	^ self commandStyledWith: #textDanger
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textHide [

	^ self commandStyledWith: #textHide
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textInfo [

	^ self commandStyledWith: #textInfo
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textJustify [

	^ self commandStyledWith: #textJustify
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textLeft [

	^ self commandStyledWith: #textLeft
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textLowercase [

	^ self commandStyledWith: #textLowercase
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textMuted [

	^ self commandStyledWith: #textMuted
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textNowrap [

	^ self commandStyledWith: #textNowrap
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textPrimary [

	^ self commandStyledWith: #textPrimary
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textRight [

	^ self commandStyledWith: #textRight
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textSuccess [

	^ self commandStyledWith: #textSuccess
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textUppercase [

	^ self commandStyledWith: #textUppercase
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> textWarning [

	^ self commandStyledWith: #textWarning
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tooltip [

	^ self commandStyledWith: #tooltip
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tooltipArrow [

	^ self commandStyledWith: #tooltipArrow
]

{ #category : #'*Willow-Bootstrap' }
ComponentClassificationCommandBuilder >> tooltipInner [

	^ self commandStyledWith: #tooltipInner
]
