"
I provide easy access to the glyhicons names
"
Class {
	#name : #Glyphicons,
	#superclass : #Object,
	#category : 'Willow-Bootstrap-WebViews'
}

{ #category : #Accessing }
Glyphicons class >> adjust [

	^'glyphicon-adjust'
]

{ #category : #Accessing }
Glyphicons class >> alert [

	^'glyphicon-alert'
]

{ #category : #Accessing }
Glyphicons class >> alignCenter [

	^'glyphicon-align-center'
]

{ #category : #Accessing }
Glyphicons class >> alignJustify [

	^'glyphicon-align-justify'
]

{ #category : #Accessing }
Glyphicons class >> alignLeft [

	^'glyphicon-align-left'
]

{ #category : #Accessing }
Glyphicons class >> alignRight [

	^'glyphicon-align-right'
]

{ #category : #Accessing }
Glyphicons class >> apple [

	^'glyphicon-apple'
]

{ #category : #Accessing }
Glyphicons class >> arrowDown [

	^'glyphicon-arrow-down'
]

{ #category : #Accessing }
Glyphicons class >> arrowLeft [

	^'glyphicon-arrow-left'
]

{ #category : #Accessing }
Glyphicons class >> arrowRight [

	^'glyphicon-arrow-right'
]

{ #category : #Accessing }
Glyphicons class >> arrowUp [

	^'glyphicon-arrow-up'
]

{ #category : #Accessing }
Glyphicons class >> asterisk [

	^'glyphicon-asterisk'
]

{ #category : #Accessing }
Glyphicons class >> babyFormula [

	^'glyphicon-baby-formula'
]

{ #category : #Accessing }
Glyphicons class >> backward [

	^'glyphicon-backward'
]

{ #category : #Accessing }
Glyphicons class >> banCircle [

	^'glyphicon-ban-circle'
]

{ #category : #Accessing }
Glyphicons class >> barcode [

	^'glyphicon-barcode'
]

{ #category : #Accessing }
Glyphicons class >> bed [

	^'glyphicon-bed'
]

{ #category : #Accessing }
Glyphicons class >> bell [

	^'glyphicon-bell'
]

{ #category : #Accessing }
Glyphicons class >> bishop [

	^'glyphicon-bishop'
]

{ #category : #Accessing }
Glyphicons class >> bitcoin [

	^'glyphicon-bitcoin'
]

{ #category : #Accessing }
Glyphicons class >> blackboard [

	^'glyphicon-blackboard'
]

{ #category : #Accessing }
Glyphicons class >> bold [

	^'glyphicon-bold'
]

{ #category : #Accessing }
Glyphicons class >> book [

	^'glyphicon-book'
]

{ #category : #Accessing }
Glyphicons class >> bookmark [

	^'glyphicon-bookmark'
]

{ #category : #Accessing }
Glyphicons class >> briefcase [

	^'glyphicon-briefcase'
]

{ #category : #Accessing }
Glyphicons class >> btc [

	^'glyphicon-btc'
]

{ #category : #Accessing }
Glyphicons class >> bullhorn [

	^'glyphicon-bullhorn'
]

{ #category : #Accessing }
Glyphicons class >> calendar [

	^'glyphicon-calendar'
]

{ #category : #Accessing }
Glyphicons class >> camera [

	^'glyphicon-camera'
]

{ #category : #Accessing }
Glyphicons class >> cd [

	^'glyphicon-cd'
]

{ #category : #Accessing }
Glyphicons class >> certificate [

	^'glyphicon-certificate'
]

{ #category : #Accessing }
Glyphicons class >> check [

	^'glyphicon-check'
]

{ #category : #Accessing }
Glyphicons class >> chevronDown [

	^'glyphicon-chevron-down'
]

{ #category : #Accessing }
Glyphicons class >> chevronLeft [

	^'glyphicon-chevron-left'
]

{ #category : #Accessing }
Glyphicons class >> chevronRight [

	^'glyphicon-chevron-right'
]

{ #category : #Accessing }
Glyphicons class >> chevronUp [

	^'glyphicon-chevron-up'
]

{ #category : #Accessing }
Glyphicons class >> circleArrowDown [

	^'glyphicon-circle-arrow-down'
]

{ #category : #Accessing }
Glyphicons class >> circleArrowLeft [

	^'glyphicon-circle-arrow-left'
]

{ #category : #Accessing }
Glyphicons class >> circleArrowRight [

	^'glyphicon-circle-arrow-right'
]

{ #category : #Accessing }
Glyphicons class >> circleArrowUp [

	^'glyphicon-circle-arrow-up'
]

{ #category : #Accessing }
Glyphicons class >> cloud [

	^'glyphicon-cloud'
]

{ #category : #Accessing }
Glyphicons class >> cloudDownload [

	^'glyphicon-cloud-download'
]

{ #category : #Accessing }
Glyphicons class >> cloudUpload [

	^'glyphicon-cloud-upload'
]

{ #category : #Accessing }
Glyphicons class >> cog [

	^'glyphicon-cog'
]

{ #category : #Accessing }
Glyphicons class >> collapseDown [

	^'glyphicon-collapse-down'
]

{ #category : #Accessing }
Glyphicons class >> collapseUp [

	^'glyphicon-collapse-up'
]

{ #category : #Accessing }
Glyphicons class >> comment [

	^'glyphicon-comment'
]

{ #category : #Accessing }
Glyphicons class >> compressed [

	^'glyphicon-compressed'
]

{ #category : #Accessing }
Glyphicons class >> console [

	^'glyphicon-console'
]

{ #category : #Accessing }
Glyphicons class >> copy [

	^'glyphicon-copy'
]

{ #category : #Accessing }
Glyphicons class >> copyrightMark [

	^'glyphicon-copyright-mark'
]

{ #category : #Accessing }
Glyphicons class >> creditCard [

	^'glyphicon-credit-card'
]

{ #category : #Accessing }
Glyphicons class >> cutlery [

	^'glyphicon-cutlery'
]

{ #category : #Accessing }
Glyphicons class >> dashboard [

	^'glyphicon-dashboard'
]

{ #category : #Accessing }
Glyphicons class >> download [

	^'glyphicon-download'
]

{ #category : #Accessing }
Glyphicons class >> downloadAlt [

	^'glyphicon-download-alt'
]

{ #category : #Accessing }
Glyphicons class >> duplicate [

	^'glyphicon-duplicate'
]

{ #category : #Accessing }
Glyphicons class >> earphone [

	^'glyphicon-earphone'
]

{ #category : #Accessing }
Glyphicons class >> edit [

	^'glyphicon-edit'
]

{ #category : #Accessing }
Glyphicons class >> education [

	^'glyphicon-education'
]

{ #category : #Accessing }
Glyphicons class >> eject [

	^'glyphicon-eject'
]

{ #category : #Accessing }
Glyphicons class >> envelope [

	^'glyphicon-envelope'
]

{ #category : #Accessing }
Glyphicons class >> equalizer [

	^'glyphicon-equalizer'
]

{ #category : #Accessing }
Glyphicons class >> erase [

	^'glyphicon-erase'
]

{ #category : #Accessing }
Glyphicons class >> eur [

	^'glyphicon-eur'
]

{ #category : #Accessing }
Glyphicons class >> euro [

	^'glyphicon-euro'
]

{ #category : #Accessing }
Glyphicons class >> exclamationSign [

	^'glyphicon-exclamation-sign'
]

{ #category : #Accessing }
Glyphicons class >> expand [

	^'glyphicon-expand'
]

{ #category : #Accessing }
Glyphicons class >> export [

	^'glyphicon-export'
]

{ #category : #Accessing }
Glyphicons class >> eyeClose [

	^'glyphicon-eye-close'
]

{ #category : #Accessing }
Glyphicons class >> eyeOpen [

	^'glyphicon-eye-open'
]

{ #category : #Accessing }
Glyphicons class >> facetimeVideo [

	^'glyphicon-facetime-video'
]

{ #category : #Accessing }
Glyphicons class >> fastBackward [

	^'glyphicon-fast-backward'
]

{ #category : #Accessing }
Glyphicons class >> fastForward [

	^'glyphicon-fast-forward'
]

{ #category : #Accessing }
Glyphicons class >> file [

	^'glyphicon-file'
]

{ #category : #Accessing }
Glyphicons class >> film [

	^'glyphicon-film'
]

{ #category : #Accessing }
Glyphicons class >> filter [

	^'glyphicon-filter'
]

{ #category : #Accessing }
Glyphicons class >> fire [

	^'glyphicon-fire'
]

{ #category : #Accessing }
Glyphicons class >> flag [

	^'glyphicon-flag'
]

{ #category : #Accessing }
Glyphicons class >> flash [

	^'glyphicon-flash'
]

{ #category : #Accessing }
Glyphicons class >> floppyDisk [

	^'glyphicon-floppy-disk'
]

{ #category : #Accessing }
Glyphicons class >> floppyOpen [

	^'glyphicon-floppy-open'
]

{ #category : #Accessing }
Glyphicons class >> floppyRemove [

	^'glyphicon-floppy-remove'
]

{ #category : #Accessing }
Glyphicons class >> floppySave [

	^'glyphicon-floppy-save'
]

{ #category : #Accessing }
Glyphicons class >> floppySaved [

	^'glyphicon-floppy-saved'
]

{ #category : #Accessing }
Glyphicons class >> folderClose [

	^'glyphicon-folder-close'
]

{ #category : #Accessing }
Glyphicons class >> folderOpen [

	^'glyphicon-folder-open'
]

{ #category : #Accessing }
Glyphicons class >> font [

	^'glyphicon-font'
]

{ #category : #Accessing }
Glyphicons class >> forward [

	^'glyphicon-forward'
]

{ #category : #Accessing }
Glyphicons class >> fullscreen [

	^'glyphicon-fullscreen'
]

{ #category : #Accessing }
Glyphicons class >> gbp [

	^'glyphicon-gbp'
]

{ #category : #Accessing }
Glyphicons class >> gift [

	^'glyphicon-gift'
]

{ #category : #Accessing }
Glyphicons class >> glass [

	^'glyphicon-glass'
]

{ #category : #Accessing }
Glyphicons class >> globe [

	^'glyphicon-globe'
]

{ #category : #Accessing }
Glyphicons class >> grain [

	^'glyphicon-grain'
]

{ #category : #Accessing }
Glyphicons class >> handDown [

	^'glyphicon-hand-down'
]

{ #category : #Accessing }
Glyphicons class >> handLeft [

	^'glyphicon-hand-left'
]

{ #category : #Accessing }
Glyphicons class >> handRight [

	^'glyphicon-hand-right'
]

{ #category : #Accessing }
Glyphicons class >> handUp [

	^'glyphicon-hand-up'
]

{ #category : #Accessing }
Glyphicons class >> hdVideo [

	^'glyphicon-hd-video'
]

{ #category : #Accessing }
Glyphicons class >> hdd [

	^'glyphicon-hdd'
]

{ #category : #Accessing }
Glyphicons class >> header [

	^'glyphicon-header'
]

{ #category : #Accessing }
Glyphicons class >> headphones [

	^'glyphicon-headphones'
]

{ #category : #Accessing }
Glyphicons class >> heart [

	^'glyphicon-heart'
]

{ #category : #Accessing }
Glyphicons class >> heartEmpty [

	^'glyphicon-heart-empty'
]

{ #category : #Accessing }
Glyphicons class >> home [

	^'glyphicon-home'
]

{ #category : #Accessing }
Glyphicons class >> hourglass [

	^'glyphicon-hourglass'
]

{ #category : #Accessing }
Glyphicons class >> iceLolly [

	^'glyphicon-ice-lolly'
]

{ #category : #Accessing }
Glyphicons class >> iceLollyTasted [

	^'glyphicon-ice-lolly-tasted'
]

{ #category : #Accessing }
Glyphicons class >> import [

	^'glyphicon-import'
]

{ #category : #Accessing }
Glyphicons class >> inbox [

	^'glyphicon-inbox'
]

{ #category : #Accessing }
Glyphicons class >> indentLeft [

	^'glyphicon-indent-left'
]

{ #category : #Accessing }
Glyphicons class >> indentRight [

	^'glyphicon-indent-right'
]

{ #category : #Accessing }
Glyphicons class >> infoSign [

	^'glyphicon-info-sign'
]

{ #category : #Accessing }
Glyphicons class >> italic [

	^'glyphicon-italic'
]

{ #category : #Accessing }
Glyphicons class >> jpy [

	^'glyphicon-jpy'
]

{ #category : #Accessing }
Glyphicons class >> king [

	^'glyphicon-king'
]

{ #category : #Accessing }
Glyphicons class >> knight [

	^'glyphicon-knight'
]

{ #category : #Accessing }
Glyphicons class >> lamp [

	^'glyphicon-lamp'
]

{ #category : #Accessing }
Glyphicons class >> leaf [

	^'glyphicon-leaf'
]

{ #category : #Accessing }
Glyphicons class >> levelUp [

	^'glyphicon-level-up'
]

{ #category : #Accessing }
Glyphicons class >> link [

	^'glyphicon-link'
]

{ #category : #Accessing }
Glyphicons class >> list [

	^'glyphicon-list'
]

{ #category : #Accessing }
Glyphicons class >> listAlt [

	^'glyphicon-list-alt'
]

{ #category : #Accessing }
Glyphicons class >> lock [

	^'glyphicon-lock'
]

{ #category : #Accessing }
Glyphicons class >> logIn [

	^'glyphicon-log-in'
]

{ #category : #Accessing }
Glyphicons class >> logOut [

	^'glyphicon-log-out'
]

{ #category : #Accessing }
Glyphicons class >> magnet [

	^'glyphicon-magnet'
]

{ #category : #Accessing }
Glyphicons class >> mapMarker [

	^'glyphicon-map-marker'
]

{ #category : #Accessing }
Glyphicons class >> menuDown [

	^'glyphicon-menu-down'
]

{ #category : #Accessing }
Glyphicons class >> menuHamburger [

	^'glyphicon-menu-hamburger'
]

{ #category : #Accessing }
Glyphicons class >> menuLeft [

	^'glyphicon-menu-left'
]

{ #category : #Accessing }
Glyphicons class >> menuRight [

	^'glyphicon-menu-right'
]

{ #category : #Accessing }
Glyphicons class >> menuUp [

	^'glyphicon-menu-up'
]

{ #category : #Accessing }
Glyphicons class >> minus [

	^'glyphicon-minus'
]

{ #category : #Accessing }
Glyphicons class >> minusSign [

	^'glyphicon-minus-sign'
]

{ #category : #Accessing }
Glyphicons class >> modalWindow [

	^'glyphicon-modal-window'
]

{ #category : #Accessing }
Glyphicons class >> move [

	^'glyphicon-move'
]

{ #category : #Accessing }
Glyphicons class >> music [

	^'glyphicon-music'
]

{ #category : #Accessing }
Glyphicons class >> newWindow [

	^'glyphicon-new-window'
]

{ #category : #Accessing }
Glyphicons class >> objectAlignBottom [

	^'glyphicon-object-align-bottom'
]

{ #category : #Accessing }
Glyphicons class >> objectAlignHorizontal [

	^'glyphicon-object-align-horizontal'
]

{ #category : #Accessing }
Glyphicons class >> objectAlignLeft [

	^'glyphicon-object-align-left'
]

{ #category : #Accessing }
Glyphicons class >> objectAlignRight [

	^'glyphicon-object-align-right'
]

{ #category : #Accessing }
Glyphicons class >> objectAlignTop [

	^'glyphicon-object-align-top'
]

{ #category : #Accessing }
Glyphicons class >> objectAlignVertical [

	^'glyphicon-object-align-vertical'
]

{ #category : #Accessing }
Glyphicons class >> off [

	^'glyphicon-off'
]

{ #category : #Accessing }
Glyphicons class >> oil [

	^'glyphicon-oil'
]

{ #category : #Accessing }
Glyphicons class >> ok [

	^'glyphicon-ok'
]

{ #category : #Accessing }
Glyphicons class >> okCircle [

	^'glyphicon-ok-circle'
]

{ #category : #Accessing }
Glyphicons class >> okSign [

	^'glyphicon-ok-sign'
]

{ #category : #Accessing }
Glyphicons class >> open [

	^'glyphicon-open'
]

{ #category : #Accessing }
Glyphicons class >> openFile [

	^'glyphicon-open-file'
]

{ #category : #Accessing }
Glyphicons class >> optionHorizontal [

	^'glyphicon-option-horizontal'
]

{ #category : #Accessing }
Glyphicons class >> optionVertical [

	^'glyphicon-option-vertical'
]

{ #category : #Accessing }
Glyphicons class >> paperclip [

	^'glyphicon-paperclip'
]

{ #category : #Accessing }
Glyphicons class >> paste [

	^'glyphicon-paste'
]

{ #category : #Accessing }
Glyphicons class >> pause [

	^'glyphicon-pause'
]

{ #category : #Accessing }
Glyphicons class >> pawn [

	^'glyphicon-pawn'
]

{ #category : #Accessing }
Glyphicons class >> pencil [

	^'glyphicon-pencil'
]

{ #category : #Accessing }
Glyphicons class >> phone [

	^'glyphicon-phone'
]

{ #category : #Accessing }
Glyphicons class >> phoneAlt [

	^'glyphicon-phone-alt'
]

{ #category : #Accessing }
Glyphicons class >> picture [

	^'glyphicon-picture'
]

{ #category : #Accessing }
Glyphicons class >> piggyBank [

	^'glyphicon-piggy-bank'
]

{ #category : #Accessing }
Glyphicons class >> plane [

	^'glyphicon-plane'
]

{ #category : #Accessing }
Glyphicons class >> play [

	^'glyphicon-play'
]

{ #category : #Accessing }
Glyphicons class >> playCircle [

	^'glyphicon-play-circle'
]

{ #category : #Accessing }
Glyphicons class >> plus [

	^'glyphicon-plus'
]

{ #category : #Accessing }
Glyphicons class >> plusSign [

	^'glyphicon-plus-sign'
]

{ #category : #Accessing }
Glyphicons class >> print [

	^'glyphicon-print'
]

{ #category : #Accessing }
Glyphicons class >> pushpin [

	^'glyphicon-pushpin'
]

{ #category : #Accessing }
Glyphicons class >> qrcode [

	^'glyphicon-qrcode'
]

{ #category : #Accessing }
Glyphicons class >> queen [

	^'glyphicon-queen'
]

{ #category : #Accessing }
Glyphicons class >> questionSign [

	^'glyphicon-question-sign'
]

{ #category : #Accessing }
Glyphicons class >> random [

	^'glyphicon-random'
]

{ #category : #Accessing }
Glyphicons class >> record [

	^'glyphicon-record'
]

{ #category : #Accessing }
Glyphicons class >> refresh [

	^'glyphicon-refresh'
]

{ #category : #Accessing }
Glyphicons class >> registrationMark [

	^'glyphicon-registration-mark'
]

{ #category : #Accessing }
Glyphicons class >> remove [

	^'glyphicon-remove'
]

{ #category : #Accessing }
Glyphicons class >> removeCircle [

	^'glyphicon-remove-circle'
]

{ #category : #Accessing }
Glyphicons class >> removeSign [

	^'glyphicon-remove-sign'
]

{ #category : #Accessing }
Glyphicons class >> repeat [

	^'glyphicon-repeat'
]

{ #category : #Accessing }
Glyphicons class >> resizeFull [

	^'glyphicon-resize-full'
]

{ #category : #Accessing }
Glyphicons class >> resizeHorizontal [

	^'glyphicon-resize-horizontal'
]

{ #category : #Accessing }
Glyphicons class >> resizeSmall [

	^'glyphicon-resize-small'
]

{ #category : #Accessing }
Glyphicons class >> resizeVertical [

	^'glyphicon-resize-vertical'
]

{ #category : #Accessing }
Glyphicons class >> retweet [

	^'glyphicon-retweet'
]

{ #category : #Accessing }
Glyphicons class >> road [

	^'glyphicon-road'
]

{ #category : #Accessing }
Glyphicons class >> rub [

	^'glyphicon-rub'
]

{ #category : #Accessing }
Glyphicons class >> ruble [

	^'glyphicon-ruble'
]

{ #category : #Accessing }
Glyphicons class >> save [

	^'glyphicon-save'
]

{ #category : #Accessing }
Glyphicons class >> saveFile [

	^'glyphicon-save-file'
]

{ #category : #Accessing }
Glyphicons class >> saved [

	^'glyphicon-saved'
]

{ #category : #Accessing }
Glyphicons class >> scale [

	^'glyphicon-scale'
]

{ #category : #Accessing }
Glyphicons class >> scissors [

	^'glyphicon-scissors'
]

{ #category : #Accessing }
Glyphicons class >> screenshot [

	^'glyphicon-screenshot'
]

{ #category : #Accessing }
Glyphicons class >> sdVideo [

	^'glyphicon-sd-video'
]

{ #category : #Accessing }
Glyphicons class >> search [

	^'glyphicon-search'
]

{ #category : #Accessing }
Glyphicons class >> send [

	^'glyphicon-send'
]

{ #category : #Accessing }
Glyphicons class >> share [

	^'glyphicon-share'
]

{ #category : #Accessing }
Glyphicons class >> shareAlt [

	^'glyphicon-share-alt'
]

{ #category : #Accessing }
Glyphicons class >> shoppingCart [

	^'glyphicon-shopping-cart'
]

{ #category : #Accessing }
Glyphicons class >> signal [

	^'glyphicon-signal'
]

{ #category : #Accessing }
Glyphicons class >> sort [

	^'glyphicon-sort'
]

{ #category : #Accessing }
Glyphicons class >> sortByAlphabet [

	^'glyphicon-sort-by-alphabet'
]

{ #category : #Accessing }
Glyphicons class >> sortByAlphabetAlt [

	^'glyphicon-sort-by-alphabet-alt'
]

{ #category : #Accessing }
Glyphicons class >> sortByAttributes [

	^'glyphicon-sort-by-attributes'
]

{ #category : #Accessing }
Glyphicons class >> sortByAttributesAlt [

	^'glyphicon-sort-by-attributes-alt'
]

{ #category : #Accessing }
Glyphicons class >> sortByOrder [

	^'glyphicon-sort-by-order'
]

{ #category : #Accessing }
Glyphicons class >> sortByOrderAlt [

	^'glyphicon-sort-by-order-alt'
]

{ #category : #Accessing }
Glyphicons class >> sound51 [

	^'glyphicon-sound-5-1'
]

{ #category : #Accessing }
Glyphicons class >> sound61 [

	^'glyphicon-sound-6-1'
]

{ #category : #Accessing }
Glyphicons class >> sound71 [

	^'glyphicon-sound-7-1'
]

{ #category : #Accessing }
Glyphicons class >> soundDolby [

	^'glyphicon-sound-dolby'
]

{ #category : #Accessing }
Glyphicons class >> soundStereo [

	^'glyphicon-sound-stereo'
]

{ #category : #Accessing }
Glyphicons class >> star [

	^'glyphicon-star'
]

{ #category : #Accessing }
Glyphicons class >> starEmpty [

	^'glyphicon-star-empty'
]

{ #category : #Accessing }
Glyphicons class >> stats [

	^'glyphicon-stats'
]

{ #category : #Accessing }
Glyphicons class >> stepBackward [

	^'glyphicon-step-backward'
]

{ #category : #Accessing }
Glyphicons class >> stepForward [

	^'glyphicon-step-forward'
]

{ #category : #Accessing }
Glyphicons class >> stop [

	^'glyphicon-stop'
]

{ #category : #Accessing }
Glyphicons class >> subscript [

	^'glyphicon-subscript'
]

{ #category : #Accessing }
Glyphicons class >> subtitles [

	^'glyphicon-subtitles'
]

{ #category : #Accessing }
Glyphicons class >> sunglasses [

	^'glyphicon-sunglasses'
]

{ #category : #Accessing }
Glyphicons class >> superscript [

	^'glyphicon-superscript'
]

{ #category : #Accessing }
Glyphicons class >> tag [

	^'glyphicon-tag'
]

{ #category : #Accessing }
Glyphicons class >> tags [

	^'glyphicon-tags'
]

{ #category : #Accessing }
Glyphicons class >> tasks [

	^'glyphicon-tasks'
]

{ #category : #Accessing }
Glyphicons class >> tent [

	^'glyphicon-tent'
]

{ #category : #Accessing }
Glyphicons class >> textBackground [

	^'glyphicon-text-background'
]

{ #category : #Accessing }
Glyphicons class >> textColor [

	^'glyphicon-text-color'
]

{ #category : #Accessing }
Glyphicons class >> textHeight [

	^'glyphicon-text-height'
]

{ #category : #Accessing }
Glyphicons class >> textSize [

	^'glyphicon-text-size'
]

{ #category : #Accessing }
Glyphicons class >> textWidth [

	^'glyphicon-text-width'
]

{ #category : #Accessing }
Glyphicons class >> th [

	^'glyphicon-th'
]

{ #category : #Accessing }
Glyphicons class >> thLarge [

	^'glyphicon-th-large'
]

{ #category : #Accessing }
Glyphicons class >> thList [

	^'glyphicon-th-list'
]

{ #category : #Accessing }
Glyphicons class >> thumbsDown [

	^'glyphicon-thumbs-down'
]

{ #category : #Accessing }
Glyphicons class >> thumbsUp [

	^'glyphicon-thumbs-up'
]

{ #category : #Accessing }
Glyphicons class >> time [

	^'glyphicon-time'
]

{ #category : #Accessing }
Glyphicons class >> tint [

	^'glyphicon-tint'
]

{ #category : #Accessing }
Glyphicons class >> tower [

	^'glyphicon-tower'
]

{ #category : #Accessing }
Glyphicons class >> transfer [

	^'glyphicon-transfer'
]

{ #category : #Accessing }
Glyphicons class >> trash [

	^'glyphicon-trash'
]

{ #category : #Accessing }
Glyphicons class >> treeConifer [

	^'glyphicon-tree-conifer'
]

{ #category : #Accessing }
Glyphicons class >> treeDeciduous [

	^'glyphicon-tree-deciduous'
]

{ #category : #Accessing }
Glyphicons class >> triangleBottom [

	^'glyphicon-triangle-bottom'
]

{ #category : #Accessing }
Glyphicons class >> triangleLeft [

	^'glyphicon-triangle-left'
]

{ #category : #Accessing }
Glyphicons class >> triangleRight [

	^'glyphicon-triangle-right'
]

{ #category : #Accessing }
Glyphicons class >> triangleTop [

	^'glyphicon-triangle-top'
]

{ #category : #Accessing }
Glyphicons class >> unchecked [

	^'glyphicon-unchecked'
]

{ #category : #Accessing }
Glyphicons class >> upload [

	^'glyphicon-upload'
]

{ #category : #Accessing }
Glyphicons class >> usd [

	^'glyphicon-usd'
]

{ #category : #Accessing }
Glyphicons class >> user [

	^'glyphicon-user'
]

{ #category : #Accessing }
Glyphicons class >> volumeDown [

	^'glyphicon-volume-down'
]

{ #category : #Accessing }
Glyphicons class >> volumeOff [

	^'glyphicon-volume-off'
]

{ #category : #Accessing }
Glyphicons class >> volumeUp [

	^'glyphicon-volume-up'
]

{ #category : #Accessing }
Glyphicons class >> warningSign [

	^'glyphicon-warning-sign'
]

{ #category : #Accessing }
Glyphicons class >> wrench [

	^'glyphicon-wrench'
]

{ #category : #Accessing }
Glyphicons class >> xbt [

	^'glyphicon-xbt'
]

{ #category : #Accessing }
Glyphicons class >> yen [

	^'glyphicon-yen'
]

{ #category : #Accessing }
Glyphicons class >> zoomIn [

	^'glyphicon-zoom-in'
]

{ #category : #Accessing }
Glyphicons class >> zoomOut [

	^'glyphicon-zoom-out'
]
